"""The whole stack on a laptop, in one command. No Docker, no admin rights.

    python scripts/dev_stack.py

It starts an embedded PostgreSQL, applies every migration, loads the seed,
loads the **real Giridih Form 20** for VS-2024 and VS-2019 (db/seed/form20/,
through ingest/load_form20_tables.py), refreshes the materialized views,
creates one user per role, prints the credentials, and serves the API on
http://localhost:8000.

    python scripts/dev_stack.py --synthetic    # the mock dataset instead (see below)
    python scripts/dev_stack.py --rebuild      # throw the database away first
    python scripts/dev_stack.py --no-serve     # build, then exit
    python scripts/dev_stack.py --url          # print DATABASE_URL and exit
    python scripts/dev_stack.py --stop         # stop the embedded server

Why this exists. Every gate in this project that needed a database was recorded
as NOT VERIFIED HERE, because the build environment has no Docker, no
PostgreSQL service and no administrator rights (DECISIONS.md D-002). The
`pgserver` wheel ships a self-contained PostgreSQL 16 that runs as an ordinary
user out of a directory, which removes that excuse entirely: migrations apply,
views refresh, the loaders run, and the API answers from real rows.

The wheel's PostgreSQL is minimal - plpgsql and pgvector, no PostGIS, no
pg_trgm, no unaccent - which is what finding N4 and the header of
0001_extensions.sql are about. The schema detects what it has and declares its
two geometry columns accordingly, so this stack is the same schema as the
deployment, not a reduced one.

**The data.** By default Giridih's booth results are the real ECI Form 20:
367 polling stations, every candidate, postal ballots. The Form 20 has no
polling-station names, electors or locations, so booths are placeholders
("PS list not loaded"), booth turnout and new-voter figures are absent, and
the map has outlines but no points - each says what it needs.

With `--synthetic`, booth-level numbers are generated by
`ingest/mock_documents.py` (registered as synthetic in source_doc) and are not
evidence about any constituency: that build proves the PDF loaders, rolls and
geocoding work, not that any figure is right.

Everything lives under `.devstack/`, which is gitignored:

    .devstack/pgdata/     the embedded PostgreSQL cluster
    .devstack/mock/       the generated source documents and their manifest
    .devstack/state.json  what has been built, so a re-run is fast
    .devstack/users.json  the dev credentials this script printed
"""

from __future__ import annotations

import argparse
import json
import os
import secrets
import subprocess
import sys
import time
from pathlib import Path

APP_ROOT = Path(__file__).resolve().parents[1]
STATE_DIR = APP_ROOT / ".devstack"
PGDATA = STATE_DIR / "pgdata"
MOCK_DIR = STATE_DIR / "mock"
STATE_FILE = STATE_DIR / "state.json"
USERS_FILE = STATE_DIR / "users.json"

DEV_DB = "giridih_dev"
# tests/e2e needs a database it may drop and rebuild. Its fixture refuses
# any URL whose name does not contain "test", so the name matters.
TEST_DB = "giridih_test"
API_PORT = 8000

# The three roles in db/migrations/0008_ops.sql, one user each, so every
# role-scoping check in tests/e2e has somebody to run as. The block user is
# deliberately NOT in the AC's first block: a scoping bug that happens to allow
# the first block would pass unnoticed.
DEV_USERS = [
    {"phone": "9000000001", "name": "Dev Admin", "role": "admin", "block": None},
    {"phone": "9000000002", "name": "Dev Strategist", "role": "strategist", "block": None},
    {"phone": "9000000003", "name": "Dev Block In-charge", "role": "block", "block": "second"},
]

# Build steps, in order. Each is recorded in state.json when it succeeds, so a
# re-run skips what is already done and `--rebuild` starts over. The order is
# not cosmetic: the PS list mints the booths the Form 20's crosswalk needs, the
# crosswalk binds the older elections' PS numbers onto those booths, and the
# roll has to be linked to an election before any turnout figure exists.
# The default build loads the REAL Giridih Form 20 (db/seed/form20/, VS-2024
# then VS-2019) through ingest.load_form20_tables. `--synthetic` builds the old
# mock dataset instead - generated PDFs through the PDF loaders, a mock roll,
# community estimates and synthetic map points - which exercises the parts of
# the pipeline the real data cannot yet (PS lists, rolls, geocoding).
STEPS_REAL = ["migrate", "seed", "form20_real", "news", "refresh", "users"]
STEPS_SYNTHETIC = ["migrate", "seed", "generate", "ps_list", "form20", "crosswalk", "roll",
                   "caste", "geo", "news", "refresh", "users"]
STEPS = STEPS_SYNTHETIC + ["form20_real"]          # every step name, for --from-step


# ---------------------------------------------------------------------------
# Plumbing
# ---------------------------------------------------------------------------

def log(message: str) -> None:
    print(f"[dev_stack] {message}", flush=True)


def fail(message: str) -> None:
    print(f"[dev_stack] ERROR {message}", file=sys.stderr, flush=True)
    raise SystemExit(1)


def read_state() -> dict:
    if STATE_FILE.exists():
        try:
            return json.loads(STATE_FILE.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            log("state.json is unreadable; treating the stack as unbuilt")
    return {"done": [], "version": 1}


def write_state(state: dict) -> None:
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    STATE_FILE.write_text(json.dumps(state, indent=2), encoding="utf-8")


def run(args: list[str], what: str, env: dict | None = None) -> None:
    """Run a loader as a subprocess and fail loudly.

    Subprocesses rather than in-process calls on purpose: these are the exact
    commands RUN.md tells an operator to type, argument parsing included. An
    in-process call would let this script drift into being a second, friendlier
    pipeline that works where the documented one does not.
    """
    log(f"$ {' '.join(str(a) for a in args[1:])}")
    proc = subprocess.run(
        [str(a) for a in args], cwd=APP_ROOT,
        env={**os.environ, **(env or {})},
        capture_output=True, text=True, encoding="utf-8", errors="replace",
    )
    if proc.returncode != 0:
        sys.stderr.write(proc.stdout or "")
        sys.stderr.write(proc.stderr or "")
        fail(f"{what} failed with exit code {proc.returncode}")
    for line in (proc.stderr or "").splitlines():
        if any(tag in line for tag in (" WARNING ", " ERROR ")) or "loaded" in line:
            print(f"    {line}", flush=True)


def _printed_password(stdout: str, phone: str) -> str:
    """Read back the password `create_admin --generate-password` printed.

    Parsing another script's stdout is not lovely. The alternative is to hash a
    password here and insert the row directly, which would mean this stack's
    users were created by a path no operator ever uses - and the login flow is
    one of the things the stack exists to exercise.
    """
    marker = f"Password for {phone}: "
    for line in (stdout or "").splitlines():
        if marker in line:
            return line.split(marker, 1)[1].strip()
    fail(f"scripts.create_admin printed no password for {phone}. Its output was:\n{stdout}")
    raise AssertionError("unreachable")


# ---------------------------------------------------------------------------
# The embedded server
# ---------------------------------------------------------------------------

def start_postgres(cleanup: str | None) -> tuple[object, str]:
    """Start (or attach to) the embedded cluster and return (server, base URI).

    `cleanup_mode=None` leaves the cluster running when this process exits,
    which is what `--no-serve` needs: the point of building the stack is to use
    it afterwards from pytest, psql or the Vite dev server. `--stop` shuts it
    down.
    """
    try:
        import pgserver
    except ModuleNotFoundError:
        fail("pgserver is not installed. It is in requirements-dev.txt:\n"
             "    .venv/Scripts/python -m pip install -r requirements-dev.txt")

    STATE_DIR.mkdir(parents=True, exist_ok=True)
    log(f"starting the embedded PostgreSQL in {PGDATA}")
    server = pgserver.get_server(PGDATA, cleanup_mode=cleanup)
    uri = server.get_uri()
    log(f"PostgreSQL is up: {uri}")
    return server, uri


def stop_postgres() -> int:
    if not (PGDATA / "PG_VERSION").exists():
        log("no cluster in .devstack/pgdata; nothing to stop")
        return 0
    import pgserver

    server = pgserver.get_server(PGDATA, cleanup_mode="stop")
    server.cleanup()
    log("stopped")
    return 0


def database_url(base_uri: str, name: str = DEV_DB) -> str:
    """`base_uri` with its database name replaced by `name`.

    Only the URL *path* is the database. On Windows pgserver hands out a TCP URI
    (`postgresql://postgres:@localhost:5432/postgres`), but on macOS and Linux it
    uses a Unix socket and puts the socket directory in the query string
    (`postgresql://postgres:@/postgres?host=/abs/path/pgdata`). Splitting the
    whole string on its last "/" therefore cut into the socket path there.
    """
    from urllib.parse import urlsplit, urlunsplit

    parts = urlsplit(base_uri)
    return urlunsplit(parts._replace(path="/" + name))


def ensure_test_database(base_uri: str) -> str:
    """The throwaway database `tests/e2e` rebuilds from scratch on every run."""
    import psycopg

    with psycopg.connect(base_uri, autocommit=True) as conn, conn.cursor() as cur:
        cur.execute("SELECT 1 FROM pg_database WHERE datname = %s", (TEST_DB,))
        if cur.fetchone() is None:
            log(f"creating {TEST_DB}")
            cur.execute(f'CREATE DATABASE "{TEST_DB}"')
    return database_url(base_uri, TEST_DB)


def ensure_database(base_uri: str, drop: bool) -> str:
    import psycopg

    url = database_url(base_uri)
    with psycopg.connect(base_uri, autocommit=True) as conn, conn.cursor() as cur:
        cur.execute("SELECT 1 FROM pg_database WHERE datname = %s", (DEV_DB,))
        exists = cur.fetchone() is not None
        if exists and drop:
            log(f"dropping {DEV_DB}")
            cur.execute("SELECT pg_terminate_backend(pid) FROM pg_stat_activity "
                        "WHERE datname = %s AND pid <> pg_backend_pid()", (DEV_DB,))
            cur.execute(f'DROP DATABASE "{DEV_DB}"')
            exists = False
        if not exists:
            log(f"creating {DEV_DB}")
            cur.execute(f'CREATE DATABASE "{DEV_DB}"')
    return url


# ---------------------------------------------------------------------------
# Build steps
# ---------------------------------------------------------------------------

def step_migrate(py: str) -> None:
    run([py, "-m", "db.apply_migrations"], "db.apply_migrations")
    report_capabilities()


def report_capabilities() -> None:
    """Say out loud which extensions this cluster has (N4).

    `vector` is required by 0001; PostGIS, pg_trgm and unaccent are not used by
    this schema (booth location is lon/lat doubles, D-006), so they are only
    reported, never needed.
    """
    import psycopg

    with psycopg.connect(os.environ["DATABASE_URL"], row_factory=psycopg.rows.dict_row) as conn:
        with conn.cursor() as cur:
            cur.execute("SELECT extname, extversion FROM pg_extension ORDER BY extname")
            rows = cur.fetchall()
    log("extensions: " + ", ".join(f"{r['extname']} {r['extversion']}" for r in rows))


def step_seed(py: str) -> None:
    run([py, "-m", "db.seed.load_seed"], "db.seed.load_seed")


def step_generate(py: str, args) -> None:
    run([py, "-m", "ingest.mock_documents", "--ac", str(args.ac),
         "--out-dir", str(MOCK_DIR), "--booths", str(args.booths),
         "--roll-booths", str(args.roll_booths), "--seed", str(args.seed)],
        "ingest.mock_documents")


def manifest() -> dict:
    path = MOCK_DIR / "manifest.json"
    if not path.exists():
        fail(f"{path} is missing. Re-run with --rebuild.")
    return json.loads(path.read_text(encoding="utf-8"))


def docs_of(kind: str) -> list[dict]:
    return [d for d in manifest()["documents"] if d["kind"] == kind]


def step_ps_list(py: str) -> None:
    """Every PS list, per block.

    One file per block because `parse_pslist` takes a single `--block` for the
    panchayats it has to create, and a panchayat filed under the wrong block
    corrupts every block rollup silently. A real CEO list is published per AC
    with a block column; reading that column is work the parser does not do yet,
    and inventing it here would hide the gap.
    """
    for d in docs_of("ps_list"):
        cmd = [py, "-m", "ingest.parse_pslist", str(MOCK_DIR / d["path"]),
               "--ac", str(d["ac"]), "--election", d["election"], "--load",
               "--block", str(d["block_id"])]
        if d["anchor"]:
            cmd.append("--anchor")
        run(cmd, f"parse_pslist {d['path']}")


def step_form20(py: str) -> None:
    """Every Form 20: parse, resolve the columns, validate, then load.

    No `--skip-ac-check` anywhere. The gate that compares each column's booth
    sum against the published AC total at tolerance zero is the one the README
    calls the reason to trust a number, and a dev stack that disabled it would
    prove nothing. `ingest/mock_documents.py` apportions by largest remainder so
    the sums land exactly.
    """
    for d in docs_of("form20"):
        run([py, "-m", "ingest.parse_form20", str(MOCK_DIR / d["path"]),
             "--ac", str(d["ac"]), "--election", d["election"], "--load", "--replace"],
            f"parse_form20 {d['path']}")


def step_crosswalk(py: str) -> None:
    """Bind the non-anchor elections' PS numbers onto the anchored booths."""
    anchors = {d["election"] for d in docs_of("ps_list") if d["anchor"]}
    done: set[tuple[int, str]] = set()
    for d in docs_of("ps_list"):
        key = (d["ac"], d["election"])
        if d["election"] in anchors or key in done:
            continue
        done.add(key)
        run([py, "-m", "ingest.crosswalk", "--ac", str(d["ac"]),
             "--election", d["election"], "--apply"],
            f"crosswalk {d['election']}")


def step_roll(py: str) -> None:
    """The mother roll, then the supplement.

    `--link-election` on the mother roll is what gives the stack any turnout at
    all: `mv_result_booth_wide` reads its denominator from the roll revision an
    election is linked to, and nothing in this repo wrote `election_roll_link`
    until that flag existed (B1).
    """
    for kind in ("roll_mother", "roll_supplement"):
        for d in docs_of(kind):
            cmd = [py, "-m", "ingest.parse_roll", str(MOCK_DIR / d["path"]),
                   "--ac", str(d["ac"]), "--election", d["election"],
                   "--revision", d["revision"], "--date", d["date"], "--load"]
            if d["supplement"]:
                cmd.append("--supplement")
            else:
                cmd += ["--link-election", d["link_election"]]
            run(cmd, f"parse_roll {d['path']}")


def step_caste(py: str) -> None:
    """Blend the surname estimates the roll loader wrote into the `blend` rows
    the dashboard reads. Without this the Community tile said "not loaded" on a
    stack that had 180 surname estimates in it. (rahul-working)"""
    run([py, "-m", "analytics.caste_estimate"], "analytics.caste_estimate")


def step_geo(py: str, args) -> None:
    """Synthetic area outlines and booth points, so the map has something to
    draw. Generated stations cannot be geocoded; see scripts/dev_geo.py."""
    run([py, "-m", "scripts.dev_geo", "--ac", str(args.ac), "--seed", str(args.seed)],
        "scripts.dev_geo")


def step_news(py: str) -> None:
    """Real news, crawled live from the configured feeds - the one dataset here
    that is not synthetic. A source that fails is recorded on news_source and
    skipped, so being offline costs the news and nothing else."""
    run([py, "-m", "news.crawl_rss", "--limit", "1500"], "news.crawl_rss")
    # Keyword labels, so /news has something to list without an Anthropic key.
    run([py, "-m", "news.label_rules"], "news.label_rules")


def step_form20_real(py: str, args) -> None:
    """Every real Form 20 in db/seed/form20/ (ingest.load_form20_tables.seed_loads):
    per AC the VS-2024 file first (it creates the booths), then the others onto
    the same booths if their station numbering is stable. Then the 2024
    polling-station list names and places AC-32's booths, and the modelled
    layers (roll, community) are fitted to what was loaded."""
    run([py, "-m", "ingest.load_form20_tables", "--all-seed"], "ingest.load_form20_tables --all-seed")
    run([py, "-m", "ingest.load_ps_list"], "ingest.load_ps_list")
    for ac, csv_name in ((32, "demography_ac32.csv"), (31, "demography_ac31.csv")):
        run([py, "-m", "ingest.load_csv", "demography",
             str(APP_ROOT / "db" / "seed" / "census" / csv_name), "--ac", str(ac)],
            f"ingest.load_csv demography AC {ac}")
    run([py, "-m", "ingest.load_csv", "candidate_profile",
         str(APP_ROOT / "db" / "seed" / "candidates" / "candidate_profiles_ac32.csv"), "--ac", "32"],
        "ingest.load_csv candidate_profile")
    run([py, "-m", "ingest.modelled_overlay", "--ac", "32"], "ingest.modelled_overlay")


def step_refresh(py: str) -> None:
    # --blocking: REFRESH ... CONCURRENTLY cannot run on a view that has never
    # been populated, which is every view in a freshly built stack. refresh.py
    # falls back on its own, but doing fourteen failed attempts first turns a
    # clean build into a wall of warnings.
    run([py, "-m", "analytics.refresh", "--blocking"], "analytics.refresh")


def step_users(py: str) -> None:
    """Bootstrap login users: single APP_USERNAME when set, else one user per role."""
    if (os.environ.get("APP_USERNAME") or "").strip():
        run([py, "-m", "scripts.ensure_single_user"], "ensure_single_user")
        return
    import psycopg

    blocks: list[dict] = []
    with psycopg.connect(os.environ["DATABASE_URL"], row_factory=psycopg.rows.dict_row) as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT b.block_id, b.name_en, a.ac_number, COUNT(bo.booth_uid) AS booths "
                "FROM block b JOIN ac a ON a.ac_id = b.ac_id "
                "LEFT JOIN area ar ON ar.block_id = b.block_id "
                "LEFT JOIN booth bo ON bo.area_id = ar.area_id "
                "GROUP BY b.block_id, b.name_en, a.ac_number "
                "HAVING COUNT(bo.booth_uid) > 0 ORDER BY b.block_id")
            blocks = [dict(r) for r in cur.fetchall()]
    if not blocks:
        fail("no block has any booth, so a block-role user would see nothing. "
             "The PS list step did not load.")

    created = []
    for spec in DEV_USERS:
        cmd = [py, "-m", "scripts.create_admin", "--phone", spec["phone"],
               "--name", spec["name"], "--role", spec["role"], "--generate-password"]
        block = None
        if spec["block"] == "second":
            block = blocks[1] if len(blocks) > 1 else blocks[0]
            cmd += ["--block", str(block["block_id"])]
        # --generate-password, and never a password piped to stdin. `getpass` on
        # Windows reads the console device directly through msvcrt and ignores
        # the process's own stdin, so feeding it a password over a pipe does not
        # fail - it blocks for ever on a prompt nobody can see.
        proc = subprocess.run(
            cmd, cwd=APP_ROOT, env=dict(os.environ), stdin=subprocess.DEVNULL,
            capture_output=True, text=True, encoding="utf-8", errors="replace",
        )
        if proc.returncode != 0:
            sys.stderr.write(proc.stdout or "")
            sys.stderr.write(proc.stderr or "")
            fail(f"could not create the {spec['role']} user")
        password = _printed_password(proc.stdout, spec["phone"])
        created.append({
            "phone": spec["phone"], "name": spec["name"], "role": spec["role"],
            "password": password,
            "block_id": block["block_id"] if block else None,
            "block_name": block["name_en"] if block else None,
            "booths_visible": block["booths"] if block else None,
        })
    USERS_FILE.write_text(json.dumps(created, indent=2), encoding="utf-8")
    # 0600 on POSIX. On Windows the file inherits the user profile's ACL, which
    # is already private; chmod is a no-op there and is not pretended otherwise.
    try:
        USERS_FILE.chmod(0o600)
    except OSError:
        pass


STEP_FUNCS = {
    "migrate": lambda py, args: step_migrate(py),
    "seed": lambda py, args: step_seed(py),
    "generate": step_generate,
    "ps_list": lambda py, args: step_ps_list(py),
    "form20": lambda py, args: step_form20(py),
    "crosswalk": lambda py, args: step_crosswalk(py),
    "roll": lambda py, args: step_roll(py),
    "caste": lambda py, args: step_caste(py),
    "geo": step_geo,
    "news": lambda py, args: step_news(py),
    "form20_real": step_form20_real,
    "refresh": lambda py, args: step_refresh(py),
    "users": lambda py, args: step_users(py),
}


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------

def summarise() -> dict:
    """What actually landed in the database. Printed, and worth reading.

    A build that "succeeded" while loading nothing is the failure mode this
    guards: every count below comes from the database, not from the generator.
    """
    import psycopg

    counts: dict[str, object] = {}
    with psycopg.connect(os.environ["DATABASE_URL"], row_factory=psycopg.rows.dict_row) as conn:
        with conn.cursor() as cur:
            for table in ("ac", "block", "area", "booth", "ps_list_entry",
                          "booth_crosswalk", "candidate", "result_booth",
                          "result_booth_meta", "roll_revision", "roll_snapshot",
                          "roll_change", "caste_estimate", "election_roll_link",
                          "review_queue"):
                cur.execute(f"SELECT COUNT(*) AS n FROM {table}")
                counts[table] = cur.fetchone()["n"]
            cur.execute(
                "SELECT election_label, COUNT(*) AS booths, "
                "       COUNT(turnout_pct) AS with_turnout, "
                "       COUNT(margin_pct) AS with_margin, "
                "       SUM(valid_votes) AS valid_votes "
                "FROM mv_result_booth_wide GROUP BY election_label ORDER BY election_label")
            counts["by_election"] = [dict(r) for r in cur.fetchall()]
            # mv_ac_summary is keyed on ac_id and election_id, not on ac_number:
            # it is one row per contest per AC, so the AC's own columns come
            # from `ac` and the baseline contest is the one to report.
            cur.execute(
                "SELECT a.ac_number, a.name_en, a.verified, s.election_label, "
                "       s.booths, s.electors, s.winner_party, s.margin_pct, s.turnout_pct "
                "FROM ac a "
                "LEFT JOIN mv_ac_summary s ON s.ac_id = a.ac_id AND s.is_baseline "
                "ORDER BY a.ac_number")
            counts["acs"] = [dict(r) for r in cur.fetchall()]
    return counts


def print_report(url: str, counts: dict, mode: str = "real") -> None:
    users = json.loads(USERS_FILE.read_text(encoding="utf-8")) if USERS_FILE.exists() else []

    print()
    print("=" * 78)
    print("  Giridih monitor - local development stack")
    print("=" * 78)
    print(f"  API            http://localhost:{API_PORT}")
    print("  Frontend       http://localhost:5173   (npm --prefix frontend run dev)")
    print(f"  DATABASE_URL   {url}")
    print()
    print("  Sign in with any of these. Passwords are regenerated on every")
    print("  --rebuild and are also in .devstack/users.json.")
    for u in users:
        where = f"  block {u['block_id']} ({u['block_name']}, {u['booths_visible']} booths)" \
            if u["block_id"] else ""
        print(f"    {u['role']:<11} {u['phone']}  {u['password']}{where}")
    print()
    print("  Loaded (counted in the database, not claimed by the generator):")
    for table in ("booth", "ps_list_entry", "booth_crosswalk", "candidate",
                  "result_booth", "roll_snapshot", "roll_change", "caste_estimate",
                  "election_roll_link", "review_queue"):
        print(f"    {table:<20} {counts[table]:>8,}")
    print()
    print("  Per election, from mv_result_booth_wide (booth counts; valid = EVM only):")
    print(f"    {'election':<12} {'booths':>7} {'turnout':>8} {'margin':>7} {'valid (EVM)':>13}")
    for row in counts["by_election"]:
        print(f"    {row['election_label']:<12} {row['booths']:>7,} "
              f"{row['with_turnout']:>8,} {row['with_margin']:>7,} "
              f"{(row['valid_votes'] or 0):>13,}")
    print()
    print("  Constituencies, from mv_ac_summary:")
    for row in counts["acs"]:
        flag = "" if row["verified"] else "  (unverified seed)"
        margin = "-" if row["margin_pct"] is None else f"{float(row['margin_pct']):.2f}%"
        print(f"    {row['ac_number']:>3}-{row['name_en']:<10} "
              f"booths={row['booths'] or 0:<5} winner={row['winner_party'] or '-':<6} "
              f"margin={margin:<8}{flag}")
    print()
    if mode == "synthetic":
        print("  Every booth-level figure above is SYNTHETIC. Only the published AC")
        print("  totals come from the seed; check them against ECI before use.")
    else:
        print("  Booth results are the real CEO Jharkhand Form 20s (db/seed/form20/), every")
        print("  candidate with a party. AC-32 booths are named and placed from the 2024")
        print("  polling-station list; booth electors and community mix are modelled to")
        print("  published totals (ingest/modelled_overlay.py, docs/status/DATA_COVERAGE.md).")
    print("=" * 78)
    print()


# ---------------------------------------------------------------------------
# Serving
# ---------------------------------------------------------------------------

def serve() -> None:
    log(f"starting uvicorn on http://localhost:{API_PORT}  (Ctrl-C to stop both the "
        f"API and PostgreSQL)")
    import uvicorn

    # Run as `python scripts/dev_stack.py`, sys.path[0] is scripts/, not the
    # backend root, and uvicorn does not add the working directory - so
    # "api.main" was not importable and the stack died after building.
    if str(APP_ROOT) not in sys.path:
        sys.path.insert(0, str(APP_ROOT))
    uvicorn.run("api.main:app", host="127.0.0.1", port=API_PORT, log_level="info")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def build_env(url: str) -> dict:
    """The environment the loaders and the API run with.

    `JWT_SECRET` is generated once per `.devstack` and kept, so a token issued
    before a rebuild still verifies and nobody has to sign in twice while
    debugging. It is a development secret in a gitignored directory and is
    never a deployment secret - `common/secrets.py` rejects the placeholder
    values from .env.example, and this is not one of them.
    """
    secret_file = STATE_DIR / "jwt_secret"
    if not secret_file.exists():
        secret_file.write_text(secrets.token_hex(32), encoding="utf-8")
        try:
            secret_file.chmod(0o600)
        except OSError:
            pass
    env = {
        "DATABASE_URL": url,
        "JWT_SECRET": secret_file.read_text(encoding="utf-8").strip(),
        "AUTH_MODE": "password",
        "CHAT_ENABLED": "false",
        "API_CORS_ORIGINS": "http://localhost:5173,http://127.0.0.1:5173",
        "RAW_DIR": str(STATE_DIR / "raw"),
        "OCR_DIR": str(STATE_DIR / "ocr"),
        "BACKUP_DIR": str(STATE_DIR / "backups"),
        "STORAGE_BACKEND": "local",
        "RETAIN_RAW_ROLLS": "true",
        "LOG_LEVEL": "INFO",
        "PYTHONIOENCODING": "utf-8",
        "PYTHONPATH": str(APP_ROOT),
    }
    for key, value in env.items():
        os.environ[key] = value
    for key in ("RAW_DIR", "OCR_DIR", "BACKUP_DIR"):
        Path(env[key]).mkdir(parents=True, exist_ok=True)
    return env


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--rebuild", action="store_true",
                    help="drop the database and the generated documents, then build again")
    ap.add_argument("--no-serve", action="store_true", help="build and exit")
    ap.add_argument("--url", action="store_true", help="print DATABASE_URL and exit")
    ap.add_argument("--test-url", action="store_true",
                    help="create the throwaway database tests/e2e needs, print its "
                         "URL and exit. Set E2E_DATABASE_URL to it.")
    ap.add_argument("--stop", action="store_true", help="stop the embedded PostgreSQL")
    ap.add_argument("--ac", type=int, default=32, help="which AC to load booth data for")
    ap.add_argument("--booths", type=int, default=120)
    ap.add_argument("--roll-booths", type=int, default=12,
                    help="booths the generated roll covers. The rest have no electors "
                         "and so no turnout, which is correct and worth seeing.")
    ap.add_argument("--seed", type=int, default=20241123)
    ap.add_argument("--from-step", choices=STEPS,
                    help="re-run from this step onwards, keeping the database")
    ap.add_argument("--synthetic", action="store_true",
                    help="build the mock dataset (generated PDFs, roll, community "
                         "estimates, map points) instead of the real Form 20")
    args = ap.parse_args(argv)

    if args.stop:
        return stop_postgres()

    # Serving keeps this process alive, so the cluster can die with it. Building
    # only must leave it running, or the stack is unusable the moment we exit.
    cleanup = "stop" if not args.no_serve else None
    server, base_uri = start_postgres(cleanup)
    url = ensure_database(base_uri, drop=args.rebuild)
    build_env(url)

    if args.url:
        print(url)
        return 0

    if args.test_url:
        # tests/e2e drops and rebuilds the schema, and its fixture refuses any
        # URL whose database name does not contain 'test'. Creating it here is
        # what makes the instructions in RUN.md work without a psql prompt.
        print(ensure_test_database(base_uri))
        return 0

    steps = STEPS_SYNTHETIC if args.synthetic else STEPS_REAL
    mode = "synthetic" if args.synthetic else "real"
    state = read_state()
    if state.get("mode", "synthetic" if state.get("done") else mode) != mode and not args.rebuild:
        fail(f"this database was built in {state.get('mode', 'synthetic')} mode; "
             f"add --rebuild to rebuild it in {mode} mode")
    if args.rebuild:
        state = {"done": [], "version": 1}
        if MOCK_DIR.exists():
            for path in MOCK_DIR.glob("*"):
                path.unlink()
    state["mode"] = mode
    if args.from_step:
        if args.from_step not in steps:
            fail(f"{args.from_step} is not a step in {mode} mode: {', '.join(steps)}")
        cut = steps.index(args.from_step)
        state["done"] = [s for s in state["done"] if s in steps and steps.index(s) < cut]

    python = sys.executable
    started = time.monotonic()
    for step in steps:
        if step in state["done"]:
            log(f"skip {step} (already done; --rebuild or --from-step {step} to redo)")
            continue
        log(f"--- {step} ---")
        STEP_FUNCS[step](python, args)
        state["done"].append(step)
        write_state(state)
    log(f"build complete in {time.monotonic() - started:.1f}s")

    print_report(url, summarise(), mode)

    if args.no_serve:
        log("PostgreSQL is left running. Stop it with: "
            "python scripts/dev_stack.py --stop")
        return 0

    try:
        serve()
    except KeyboardInterrupt:
        log("stopping")
    finally:
        del server
    return 0


if __name__ == "__main__":
    sys.exit(main())
