"""Generate synthetic source documents for local development.

    python -m ingest.mock_documents --ac 32 --out-dir raw/mock

What it writes, for one constituency:

  * a **polling-station list** per block, per election, as a ruled-table PDF;
  * a **Form 20** per election, as a ruled-table PDF, whose per-column sums
    equal the published AC totals in `result_ac_total` exactly;
  * a **mother electoral roll** and one **supplement**, as flowed-text PDFs,
    covering the first few booths at a realistic elector density;
  * `manifest.json`, which `scripts/dev_stack.py` reads to know what to load and
    in which order.

Why generate documents rather than insert rows. Everything this product shows is
derived, and the derivation starts at a PDF: column resolution (3.1), the
booth-sum-versus-published-total gate (LLD 4.2), the crosswalk, the roll
aggregation. A fixture that inserts into `result_booth` skips all of it, which is
how C1 - every candidate loaded with a NULL party, every booth reporting a 100%
margin - survived a green test suite, and how `parse_pslist`, `parse_roll` and
`parse_form20` each came to contain inserts that the NOT NULL constraints added
in 0014 reject outright. Going in through the front door is the only way the
loaders get exercised.

**These documents are synthetic and say so on every page.** Every figure except
the published AC totals is invented by the deterministic generator below. Nothing
here is evidence about Giridih, and `--seed` fixes the output so two developers
building the stack see the same numbers.

Deliberate limitations, all of which `UAT_READINESS.md` records:

  * **Latin script only.** `common/pdf_writer.py` has the base-14 fonts and no
    Devanagari, so the Devanagari branches of `ingest/resolve.py` and
    `ingest/parse_roll.py` are not exercised by this generator. They are covered
    by the unit tests, which pass Devanagari strings directly.
  * **Ruled tables with a clean text layer.** No OCR path, no skew, no merged
    cells. A real CEO PDF is worse than this in ways no generator will guess.
  * **The roll covers a few booths, not the whole electorate.** Giridih's
    published electorate is 304,898, and a roll PDF that enumerates every one of
    them is about 4,500 pages. The booths outside the roll have NULL electors
    and therefore no turnout, which is the correct behaviour (B4) and worth
    seeing on the page.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path

from common.logging_setup import get_logger
from common.pdf_writer import (
    A4_LANDSCAPE,
    A4_PORTRAIT,
    Page,
    PdfBuilder,
    Table,
    text_width,
)

log = get_logger(__name__)

SYNTHETIC_BANNER = (
    "SYNTHETIC TEST DOCUMENT - generated by ingest/mock_documents.py. "
    "Not a real election record. Do not cite."
)

# EPIC numbers use a ZZZ prefix, which the ECI does not issue, so a string from
# one of these documents can never be mistaken for a real elector identifier -
# including by `ingest/validate.py --privacy`, which hunts for exactly this
# pattern on disk.
EPIC_PREFIX = "ZZZ"

# Surnames that exist in db/seed/surname_dict.csv, so the caste estimator has
# something to match and the Caste pages are not empty in a dev stack. Spread
# across communities on purpose: a single-community mock would make the
# low-confidence greying and the UNMATCHED share impossible to look at.
SURNAMES = [
    "Mahato", "Yadav", "Singh", "Ansari", "Murmu", "Prasad", "Devi", "Verma",
    "Ravidas", "Soren", "Khan", "Sahu", "Gupta", "Marandi", "Paswan", "Turi",
    "Mandal", "Thakur", "Hembrom", "Kumhar",
]
GIVEN_NAMES = [
    "Ram", "Sita", "Mohan", "Gita", "Suresh", "Kiran", "Rajesh", "Anita",
    "Dinesh", "Pooja", "Mukesh", "Rekha", "Santosh", "Sunita", "Vikash", "Asha",
]
BUILDING_KINDS = [
    "Primary School", "Middle School", "High School", "Panchayat Bhawan",
    "Anganwadi Kendra", "Community Hall", "Upgraded Middle School",
]
# Clearly invented place names: no real Giridih panchayat is called any of
# these, so an operator who sees one on a page knows at once it is mock data.
PLACE_STEMS = [
    "Testpur", "Mockganj", "Fixturebad", "Sampledih", "Dummytola", "Stubnagar",
    "Probepur", "Fakeganj", "Devtola", "Localdih", "Seedpur", "Scratchganj",
]


# ---------------------------------------------------------------------------
# Deterministic pseudo-randomness
#
# `random.Random` would do, but its stream is an implementation detail of the
# standard library; a CPython upgrade that reshuffles it would silently change
# every number in a dev stack and in any test that asserts on one. A named hash
# is reproducible across versions and machines, which is the only property this
# needs.
# ---------------------------------------------------------------------------

def _hash(*parts: object) -> int:
    import hashlib

    key = "|".join(str(p) for p in parts).encode("utf-8")
    return int.from_bytes(hashlib.sha256(key).digest()[:8], "big")


def unit(*parts: object) -> float:
    """A stable float in [0, 1) from the given parts."""
    return _hash(*parts) / 2**64


def pick(items: list, *parts: object):
    return items[_hash(*parts) % len(items)]


def apportion(total: int, weights: list[float]) -> list[int]:
    """Split `total` across `weights` so the parts sum to exactly `total`.

    Largest-remainder, because the Form 20 gate compares the booth sum with the
    published AC total at tolerance zero (LLD 4.2). Rounding each share
    independently would miss by a few votes and the generator would produce
    documents that its own loader refuses - which is a fine test of the gate and
    a useless way to build a dev stack.
    """
    if total == 0 or not weights:
        return [0] * len(weights)
    positive = [max(w, 0.0) for w in weights]
    mass = sum(positive)
    if mass <= 0:
        positive = [1.0] * len(weights)
        mass = float(len(weights))
    exact = [total * w / mass for w in positive]
    floors = [int(math.floor(x)) for x in exact]
    shortfall = total - sum(floors)
    order = sorted(range(len(weights)), key=lambda i: (-(exact[i] - floors[i]), i))
    for k in range(shortfall):
        floors[order[k % len(order)]] += 1
    return floors


# ---------------------------------------------------------------------------
# The constituency model
# ---------------------------------------------------------------------------

@dataclass
class Station:
    ps_number: int
    block_id: int
    block_name: str
    area: str
    building: str
    village: str
    roll_part: int


@dataclass
class Contestant:
    """One Form 20 column."""

    header: str              # exactly what the header cell prints
    published_votes: int | None
    is_seeded: bool


@dataclass
class ElectionPlan:
    label: str
    contestants: list[Contestant]
    published_nota: int | None
    stations: list[Station]
    # ps_number -> per-column votes, nota, rejected
    rows: dict[int, dict] = field(default_factory=dict)


def build_stations(ac_number: int, blocks: list[dict], wards: list[str],
                   count: int, seed: int) -> list[Station]:
    """`count` polling stations spread over this AC's blocks.

    Stations in an urban block are filed under a seeded ward name, which
    `parse_pslist.resolve_area` matches through `area_alias`. Rural stations get
    an invented panchayat name, which it creates - which is the behaviour
    db/seed/README.md asks for, since inventing panchayat names in the seed
    would silently corrupt every rollup.
    """
    if not blocks:
        raise ValueError("this AC has no blocks seeded; add them to db/seed/ac_blocks.csv")

    stations: list[Station] = []
    # Proportional split, so a three-block AC does not put everything in one.
    shares = apportion(count, [1.0] * len(blocks))
    ps = 1
    for block, n in zip(blocks, shares, strict=True):
        urban = block["kind"] == "ulb"
        for k in range(n):
            if urban and wards:
                area = wards[k % len(wards)]
                village = area
            else:
                stem = pick(PLACE_STEMS, seed, ac_number, block["block_id"], k // 4)
                area = f"{stem} Panchayat"
                village = stem if k % 3 == 0 else f"{stem} {'ABCDEFGH'[k % 8]}"
            stations.append(Station(
                ps_number=ps,
                block_id=block["block_id"],
                block_name=block["name_en"],
                area=area,
                building=f"{pick(BUILDING_KINDS, seed, ac_number, ps)} {village}",
                village=village,
                roll_part=ps,
            ))
            ps += 1
    return stations


def churn_stations(stations: list[Station], label: str, seed: int,
                   renamed: int, replaced: int) -> list[Station]:
    """An older election's list: same places, renumbered, a few changed.

    Without this every list is identical, every crosswalk match is exact, and
    the review queue, the fuzzy band and `booth_lineage` are all empty - so the
    Admin review queue has nothing to act on and B2 (a station scoring between
    0.65 and 0.85 being dropped instead of queued) cannot be seen at all.

    Three kinds of change, matching what actually happens between revisions:

      * **renumbered.** PS numbers are reversed within each block. This is the
        crosswalk's entire reason for existing (B3), and it means the match has
        to come from the name, not the number.
      * **renamed.** The building kind changes but the village does not, so the
        score lands in the fuzzy band and the row is loaded with reviewed=false.
      * **replaced.** Both building and village are new, so nothing matches and
        the crosswalk mints a booth with method 'new'.
    """
    by_block: dict[int, list[Station]] = {}
    for s in stations:
        by_block.setdefault(s.block_id, []).append(s)

    out: list[Station] = []
    for block_id, group in by_block.items():
        numbers = [s.ps_number for s in group]
        for s, number in zip(group, reversed(numbers), strict=True):
            out.append(Station(**{**asdict(s), "ps_number": number, "roll_part": number}))
        del block_id

    out.sort(key=lambda s: s.ps_number)
    touched = sorted(
        range(len(out)),
        key=lambda i: unit(seed, label, "churn", out[i].ps_number),
    )[: renamed + replaced]

    for rank, index in enumerate(touched):
        s = out[index]
        if rank < renamed:
            kinds = [k for k in BUILDING_KINDS if not s.building.startswith(k)]
            s.building = f"{pick(kinds, seed, label, s.ps_number, 'rename')} {s.village}"
        else:
            stem = pick(PLACE_STEMS, seed, label, s.ps_number, "replace")
            s.village = f"{stem} Extension"
            s.building = f"{pick(BUILDING_KINDS, seed, label, s.ps_number, 'nb')} {s.village}"
    return out


def plan_election(label: str, contestants: list[Contestant], published_nota: int | None,
                  stations: list[Station], seed: int, ac_number: int) -> ElectionPlan:
    """Decide every number this election's Form 20 will print.

    Per column, the published AC total is apportioned across booths with a
    smooth spatial profile unique to that column, so the diverging map ramp and
    the margin distribution have structure rather than noise. The apportionment
    is exact, so each column sums to its published total and the LLD 4.2 gate
    passes for the right reason.
    """
    plan = ElectionPlan(label=label, contestants=contestants,
                        published_nota=published_nota, stations=stations)
    n = len(stations)
    if n == 0:
        return plan

    columns: list[list[int]] = []
    for c in contestants:
        phase = 2 * math.pi * unit(seed, ac_number, label, c.header, "phase")
        weights = [
            1.0 + 0.45 * math.sin(2 * math.pi * i / max(n, 1) + phase)
                + 0.20 * math.sin(6 * math.pi * i / max(n, 1) + phase * 1.7)
                + 0.10 * unit(seed, label, c.header, i)
            for i in range(n)
        ]
        if c.published_votes is not None:
            total = c.published_votes
        else:
            # An unseeded column (an independent) has no published total, so one
            # is invented: a small, deterministic share of the largest seeded
            # column. Flagged as not cross-checked by ac_totals_by_column.
            biggest = max((x.published_votes or 0) for x in contestants) or 1000 * n
            total = int(biggest * (0.01 + 0.03 * unit(seed, label, c.header, "share")))
        columns.append(apportion(total, weights))

    nota_weights = [1.0 + 0.3 * unit(seed, label, "nota", i) for i in range(n)]
    nota = apportion(published_nota, nota_weights) if published_nota else [0] * n

    for i, station in enumerate(stations):
        votes = [col[i] for col in columns]
        nota_i = nota[i]
        valid = sum(votes) + nota_i
        # Rejected votes are a tiny fraction, and zero at some booths, because
        # metric_votes_polled adds them to the valid total and a column that is
        # never zero would hide a NULL-versus-zero mistake.
        rejected = 0 if i % 7 == 0 else int(valid * (0.0005 + 0.0025 * unit(seed, label, "rej", i)))
        plan.rows[station.ps_number] = {
            "votes": votes,
            "nota": nota_i,
            "rejected": rejected,
            "total_valid": valid,
            "total": valid + rejected,
            "tendered": 1 if i % 23 == 0 else 0,
        }
    return plan


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

PS_LIST_HEADER = ["Serial No. of Polling Station", "Name of Polling Station / Building",
                  "Village or Ward covered", "Part No."]


def render_ps_list(ac_number: int, ac_name: str, label: str, block_name: str,
                   stations: list[Station], rows_per_page: int = 28) -> bytes:
    builder = PdfBuilder()
    for start in range(0, len(stations), rows_per_page):
        chunk = stations[start:start + rows_per_page]
        table = Table(
            rows=[PS_LIST_HEADER] + [
                [str(s.ps_number), f"{s.building}, {s.village}", s.area, str(s.roll_part)]
                for s in chunk
            ],
            widths=[70, 300, 200, 60],
            font_size=8,
        )
        builder.add(Page(
            size=A4_LANDSCAPE,
            titles=[f"LIST OF POLLING STATIONS - {label}",
                    f"Assembly Constituency {ac_number}-{ac_name}, {block_name}",
                    SYNTHETIC_BANNER],
            table=table,
        ))
    return builder.to_bytes()


def render_form20(ac_number: int, ac_name: str, plan: ElectionPlan,
                  rows_per_page: int = 22) -> bytes:
    """A Form 20 in the column order Jharkhand prints.

    The tail columns and their labels matter more than they look: `TAIL_LABELS`
    in parse_form20 decides where the candidate run stops, so "Total of Valid
    Votes" has to come immediately after the last candidate and NOTA has to be
    in the tail, not among the candidates.
    """
    header = (["Serial No. of Polling Station"]
              + [c.header for c in plan.contestants]
              + ["Total of Valid Votes", "No. of Rejected Votes", "NOTA", "Total",
                 "No. of Tendered Votes"])
    n_cand = len(plan.contestants)
    widths = ([52] + [max(58, int(620 / max(n_cand, 1))) for _ in range(n_cand)]
              + [58, 58, 40, 52, 52])

    builder = PdfBuilder()
    for start in range(0, len(plan.stations), rows_per_page):
        chunk = plan.stations[start:start + rows_per_page]
        body = []
        for s in chunk:
            r = plan.rows[s.ps_number]
            body.append([str(s.ps_number)] + [str(v) for v in r["votes"]]
                        + [str(r["total_valid"]), str(r["rejected"]), str(r["nota"]),
                           str(r["total"]), str(r["tendered"])])
        builder.add(Page(
            size=A4_LANDSCAPE,
            titles=[f"FORM 20 - FINAL RESULT SHEET - {plan.label}",
                    f"Assembly Constituency {ac_number}-{ac_name}",
                    SYNTHETIC_BANNER],
            table=Table(rows=[header] + body, widths=widths, font_size=6.5),
        ))
    return builder.to_bytes()


def _elector_line(index: int, seed: int, label: str, ps_number: int) -> str:
    """One roll entry, in the shape `ingest/parse_roll` reads.

    The anchors are load-bearing. `NAME_RE` stops the elector name at a
    two-space gap or at one of a fixed set of following labels, and a PDF text
    layer does not promise to preserve a run of spaces - so every name here is
    followed by `House:`, a label the regex knows, rather than by whitespace.
    `RELATIVE_RE` then removes the "Father Name:" span before the name is read,
    which is what stops a father's surname being counted as an elector's.
    """
    given = pick(GIVEN_NAMES, seed, label, ps_number, index, "given")
    surname = pick(SURNAMES, seed, label, ps_number, index // 3, "surname")
    relative = pick(GIVEN_NAMES, seed, label, ps_number, index, "rel")
    epic = f"{EPIC_PREFIX}{(_hash(seed, label, ps_number, index) % 9_000_000) + 1_000_000}"
    # Ages skew the way a real electorate does: more 20-45 than 60+, and a small
    # 18-19 band, so the age-band chart is not flat.
    u = unit(seed, label, ps_number, index, "age")
    age = int(18 + 62 * (u**1.6))
    gender = "Female" if unit(seed, label, ps_number, index, "sex") < 0.48 else "Male"
    if unit(seed, label, ps_number, index, "sex3") > 0.998:
        gender = "Other"
    # Field order matters. RELATIVE_RE strips from "Father Name:" up to the
    # next House/Age/Gender label or end of line, so the relative must be
    # followed by one of those - put it last and the strip would run to the end
    # of the line and swallow the next elector on the same row.
    return (f"{epic} Name: {given} {surname} Father Name: {relative} {surname} "
            f"House: {1 + index % 180} Age: {age} Gender: {gender}")


ENTRIES_PER_LINE = 3
# 64 lines of 5.5pt with 1.35 leading leaves about 50pt of bottom margin on A4
# landscape after four title lines. `test_mock_documents` asserts that the last
# entry of a full page is still read back, so a change here that pushes text off
# the page fails a test rather than silently losing electors.
ROLL_LINES_PER_PAGE = 64
ROLL_FONT = 5.5
ROLL_MARGIN = 14.0


def _elector_row(start: int, count: int, seed: int, label: str, ps_number: int) -> str:
    """Several entries on one line, which is how a roll is actually printed.

    A real roll puts three electors across a row, and `parse_roll` is written
    for exactly that: `scan_mother_roll` counts the EPIC numbers on a line and
    `_attrs_for` pulls that many genders, ages and names from the same line,
    widening forward only when the line is short. One entry per line exercises
    none of it - so a mock that did it would leave the branch the parser exists
    for untested, and that is the branch C7 lived in: gender and age read from a
    different line than the EPIC count.

    Three per line also cuts the page count to a third, which on a document that
    enumerates tens of thousands of electors is the difference between a dev
    stack that builds in half a minute and one that takes three.
    """
    return "   ".join(_elector_line(start + k, seed, label, ps_number)
                      for k in range(count))


def _assert_row_fits(row: str, page_width: float) -> None:
    """A row that overflows gets wrapped, and a wrap mid-entry is a silent fault.

    `PdfBuilder` wraps any body line too wide for the page. For a roll that
    would split one elector's entry across two lines, putting the EPIC on one
    and the gender on the next, and the counts would come out wrong in a way
    that looks like a parser bug. Fail at generation time instead.
    """
    usable = page_width - 2 * ROLL_MARGIN
    width = text_width(row, ROLL_FONT)
    if width > usable:
        raise ValueError(
            f"a roll row is {width:.0f}pt wide and the page allows {usable:.0f}pt, so it "
            f"would wrap and split an elector entry across two lines. Shorten the entry "
            f"shape in _elector_line, lower ROLL_FONT, or reduce ENTRIES_PER_LINE."
        )


def render_roll(ac_number: int, ac_name: str, revision_label: str,
                stations: list[Station], electors: dict[int, int],
                seed: int, lines_per_page: int = ROLL_LINES_PER_PAGE) -> bytes:
    per_page = lines_per_page * ENTRIES_PER_LINE
    builder = PdfBuilder()
    for s in stations:
        total = electors.get(s.ps_number, 0)
        if total <= 0:
            continue
        written = 0
        page_index = 0
        while written < total:
            batch = min(per_page, total - written)
            body = [
                _elector_row(written + offset, min(ENTRIES_PER_LINE, batch - offset),
                             seed, revision_label, s.ps_number)
                for offset in range(0, batch, ENTRIES_PER_LINE)
            ]
            for row in body:
                _assert_row_fits(row, A4_LANDSCAPE[0])
            builder.add(Page(
                size=A4_LANDSCAPE,
                body_size=ROLL_FONT,
                margin=ROLL_MARGIN,
                titles=[f"ELECTORAL ROLL {revision_label} - {ac_number}-{ac_name}",
                        f"Polling Station No. {s.ps_number}   Part No. {s.roll_part}",
                        f"{s.building}, {s.village}   Page {page_index + 1}",
                        SYNTHETIC_BANNER],
                title_size=7.0,
                body=body,
            ))
            written += batch
            page_index += 1
    if not builder.pages:
        raise ValueError("the roll would have no pages: no booth was given an elector count")
    return builder.to_bytes()


def render_supplement(ac_number: int, ac_name: str, revision_label: str,
                      stations: list[Station], electors: dict[int, int],
                      seed: int) -> bytes:
    """A supplement: additions, deletions and modifications under headings.

    One page per station, with all three section headings present. C8 is why
    every station gets its own page with its own headings: the section state
    used to reset per PS group, so every group after the first recorded zero
    additions - a defect only a multi-station document can show.

    One entry per line here, unlike the mother roll. `_deletion_reason` reads a
    reason per *line* and applies it to every entry on it, which is audit
    finding C9 and still open; printing three deletions to a line would bake
    that behaviour into the fixture and make the per-reason counts meaningless.
    A supplement is a few dozen entries per station, so the page count this
    costs does not matter.
    """
    builder = PdfBuilder()
    for s in stations:
        base = electors.get(s.ps_number, 0)
        if base <= 0:
            continue
        n_add = max(2, int(base * (0.010 + 0.020 * unit(seed, "add", s.ps_number))))
        n_del = max(1, int(base * (0.004 + 0.008 * unit(seed, "del", s.ps_number))))
        n_mod = max(1, int(base * (0.002 + 0.004 * unit(seed, "mod", s.ps_number))))

        body: list[str] = ["ADDITIONS"]
        body += [_elector_line(k, seed, f"{revision_label}-add", s.ps_number)
                 for k in range(n_add)]
        body.append("DELETIONS")
        for k in range(n_del):
            reason = ("DEAD" if k % 3 == 0 else "SHIFTED" if k % 3 == 1 else "REPEATED")
            body.append(_elector_line(k, seed, f"{revision_label}-del", s.ps_number)
                        + f" Reason: {reason}")
        body.append("MODIFICATIONS")
        body += [_elector_line(k, seed, f"{revision_label}-mod", s.ps_number)
                 for k in range(n_mod)]

        # Chunked so a station with many additions does not overflow one page.
        for start in range(0, len(body), 64):
            builder.add(Page(
                size=A4_PORTRAIT,
                body_size=7.0,
                titles=[f"SUPPLEMENT {revision_label} - {ac_number}-{ac_name}",
                        f"Polling Station No. {s.ps_number}   Part No. {s.roll_part}",
                        SYNTHETIC_BANNER],
                body=body[start:start + 64],
            ))
    if not builder.pages:
        raise ValueError("the supplement would have no pages")
    return builder.to_bytes()


# ---------------------------------------------------------------------------
# Reading what the seed already knows
# ---------------------------------------------------------------------------

def read_ac(cur, ac_number: int) -> dict:
    cur.execute("SELECT ac_id, name_en FROM ac WHERE ac_number = %s", (ac_number,))
    row = cur.fetchone()
    if row is None:
        raise ValueError(f"AC {ac_number} is not seeded; run db.seed.load_seed first")
    cur.execute(
        "SELECT block_id, name_en, kind FROM block WHERE ac_id = %s ORDER BY block_id",
        (row["ac_id"],),
    )
    blocks = [dict(b) for b in cur.fetchall()]
    cur.execute(
        "SELECT name_en FROM area WHERE ac_id = %s AND kind = 'ward' ORDER BY area_id",
        (row["ac_id"],),
    )
    wards = [w["name_en"] for w in cur.fetchall()]
    return {"ac_id": row["ac_id"], "name_en": row["name_en"], "blocks": blocks, "wards": wards}


def read_contestants(cur, ac_id: int, label: str,
                     independents: int) -> tuple[list[Contestant], int | None] | None:
    """The Form 20 columns for one election, from the published AC totals.

    Returns None when the election has no published candidate totals: the mock
    Form 20 would then have nothing to reconcile against, and a document with
    invented totals for every column is worse than no document, because it would
    make the LLD 4.2 gate look like it had passed on real figures.

    Headers print the bare candidate name, which is what a real Form 20 carries
    and what makes `resolve.py` step 3 - fuzzy-match the name against the seeded
    candidates - the path that actually runs.
    """
    cur.execute(
        "SELECT c.name_en, p.abbr, t.value AS votes, t.metric "
        "FROM result_ac_total t "
        "JOIN election e ON e.election_id = t.election_id "
        "LEFT JOIN candidate c ON c.candidate_id = t.candidate_id "
        "LEFT JOIN party p ON p.party_id = c.party_id "
        "WHERE e.ac_id = %s AND e.label = %s AND t.metric IN ('votes', 'nota') "
        "ORDER BY t.value DESC",
        (ac_id, label),
    )
    contestants: list[Contestant] = []
    nota: int | None = None
    for row in cur.fetchall():
        if row["metric"] == "nota":
            nota = row["votes"]
        elif row["name_en"]:
            contestants.append(Contestant(header=row["name_en"],
                                          published_votes=row["votes"], is_seeded=True))
    if not contestants:
        return None

    for k in range(independents):
        given = pick(GIVEN_NAMES, label, "ind", k)
        surname = pick(SURNAMES, label, "ind", k, "s")
        contestants.append(Contestant(header=f"{given} {surname} (IND)",
                                      published_votes=None, is_seeded=False))
    return contestants, nota


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def generate(ac_number: int, out_dir: Path, booths: int, roll_booths: int,
             elections: list[str], independents: int, seed: int,
             turnout_low: float, turnout_high: float,
             renamed: int = 4, replaced: int = 2) -> dict:
    from common.db import cursor

    out_dir.mkdir(parents=True, exist_ok=True)
    documents: list[dict] = []

    with cursor() as cur:
        ac = read_ac(cur, ac_number)
        anchor_stations = build_stations(ac_number, ac["blocks"], ac["wards"], booths, seed)

        # The newest election's list is the anchor: it is what mints booth_uids.
        # Older lists are renumbered and partly changed by churn_stations, then
        # bound to those booths by ingest/crosswalk.py, which is the only safe
        # way to re-number (B5).
        anchor_label = elections[0]
        plans: dict[str, ElectionPlan] = {}
        for label in elections:
            found = read_contestants(cur, ac["ac_id"], label, independents)
            if found is None:
                log.warning("%s has no published candidate totals for AC %s - skipping. "
                            "Add them to db/seed/ac_totals.csv to include it.",
                            label, ac_number)
                continue
            contestants, nota = found
            stations = (anchor_stations if label == anchor_label
                        else churn_stations(anchor_stations, label, seed, renamed, replaced))
            plans[label] = plan_election(label, contestants, nota, stations, seed, ac_number)
            log.info("%s: %d station(s), %d column(s), %s", label, len(stations),
                     len(contestants),
                     ", ".join(f"{c.header}={c.published_votes}" for c in contestants))

    if not plans:
        raise ValueError(
            f"AC {ac_number} has no election with published candidate totals, so no "
            f"Form 20 can be generated. db/seed/ac_totals.csv is where they go."
        )
    if anchor_label not in plans:
        raise ValueError(
            f"{anchor_label} must have published candidate totals: it is the first "
            f"election given and therefore the anchor whose PS list mints the booths."
        )

    # -- PS lists, one per block per election ------------------------------
    for label, plan in plans.items():
        for block in ac["blocks"]:
            subset = [s for s in plan.stations if s.block_id == block["block_id"]]
            if not subset:
                continue
            slug = block["name_en"].lower().replace(" ", "-")
            path = out_dir / f"ps_list_{ac_number}_{label}_{slug}.pdf"
            path.write_bytes(render_ps_list(ac_number, ac["name_en"], label,
                                            block["name_en"], subset))
            documents.append({
                "kind": "ps_list", "path": path.name, "election": label,
                "ac": ac_number, "block_id": block["block_id"],
                "block_name": block["name_en"], "stations": len(subset),
                "anchor": label == anchor_label,
            })

    # -- Form 20 per election ----------------------------------------------
    for label, plan in plans.items():
        path = out_dir / f"form20_{ac_number}_{label}.pdf"
        path.write_bytes(render_form20(ac_number, ac["name_en"], plan))
        checks = {c.header: c.published_votes for c in plan.contestants if c.is_seeded}
        documents.append({
            "kind": "form20", "path": path.name, "election": label, "ac": ac_number,
            "stations": len(plan.stations), "columns": len(plan.contestants),
            "published_checks": checks, "published_nota": plan.published_nota,
        })

    # -- Roll: mother plus one supplement, over the first few booths -------
    baseline = anchor_label
    covered = plans[baseline].stations[:max(0, roll_booths)]
    electors: dict[int, int] = {}
    for s in covered:
        row = plans[baseline].rows[s.ps_number]
        polled = row["total_valid"] + row["rejected"]
        share = turnout_low + (turnout_high - turnout_low) * unit(seed, "turnout", s.ps_number)
        electors[s.ps_number] = max(polled + 1, int(round(polled / share)))

    if covered:
        mother_label = f"{baseline}-MOTHER"
        path = out_dir / f"roll_mother_{ac_number}.pdf"
        path.write_bytes(render_roll(ac_number, ac["name_en"], mother_label,
                                     covered, electors, seed))
        documents.append({
            "kind": "roll_mother", "path": path.name, "ac": ac_number,
            "election": baseline, "revision": mother_label,
            "date": "2024-01-05", "supplement": False,
            "booths": len(covered), "electors": sum(electors.values()),
            # The baseline election reads its electors through
            # election_roll_link, so dev_stack links this revision to it.
            "link_election": baseline,
        })

        supp_label = f"{baseline}-SUPP-1"
        path = out_dir / f"roll_supplement_{ac_number}.pdf"
        path.write_bytes(render_supplement(ac_number, ac["name_en"], supp_label,
                                           covered, electors, seed))
        documents.append({
            "kind": "roll_supplement", "path": path.name, "ac": ac_number,
            "election": baseline, "revision": supp_label,
            "date": "2024-10-15", "supplement": True, "booths": len(covered),
        })

    manifest = {
        "generator": "ingest/mock_documents.py",
        "synthetic": True,
        "ac": ac_number,
        "ac_name": ac["name_en"],
        "seed": seed,
        "booths": len(anchor_stations),
        "roll_booths": len(covered),
        "elections": list(plans),
        "stations": [asdict(s) for s in anchor_stations],
        "documents": documents,
    }
    (out_dir / "manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
    return manifest


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="Generate synthetic Form 20, PS list and roll PDFs for local development",
        epilog="Needs DATABASE_URL and a seeded database: the published AC totals the "
               "Form 20 must reconcile to are read from result_ac_total.",
    )
    ap.add_argument("--ac", type=int, default=32, help="AC number (default 32, Giridih)")
    ap.add_argument("--out-dir", default="raw/mock", help="where to write the PDFs")
    ap.add_argument("--booths", type=int, default=120,
                    help="polling stations in the generated AC (default 120)")
    ap.add_argument("--roll-booths", type=int, default=12,
                    help="how many booths the electoral roll covers (default 12). "
                         "The rest get NULL electors and no turnout, which is correct "
                         "and worth seeing.")
    ap.add_argument("--elections", default="VS-2024,VS-2019,VS-2014",
                    help="comma-separated election labels, baseline first")
    ap.add_argument("--independents", type=int, default=2,
                    help="extra independent columns per Form 20 (default 2)")
    ap.add_argument("--renamed", type=int, default=4,
                    help="stations whose building changes in an older list, so the "
                         "crosswalk scores them in the review band (default 4)")
    ap.add_argument("--replaced", type=int, default=2,
                    help="stations replaced outright in an older list, so the "
                         "crosswalk has to mint a booth (default 2)")
    ap.add_argument("--seed", type=int, default=20241123,
                    help="fixes every generated number")
    ap.add_argument("--turnout-low", type=float, default=0.56)
    ap.add_argument("--turnout-high", type=float, default=0.78)
    args = ap.parse_args(argv)

    try:
        manifest = generate(
            ac_number=args.ac, out_dir=Path(args.out_dir), booths=args.booths,
            roll_booths=args.roll_booths,
            elections=[e.strip() for e in args.elections.split(",") if e.strip()],
            independents=args.independents, seed=args.seed,
            turnout_low=args.turnout_low, turnout_high=args.turnout_high,
            renamed=args.renamed, replaced=args.replaced,
        )
    except ValueError as exc:
        log.error("%s", exc)
        return 2

    log.info("wrote %d document(s) for AC %s-%s into %s",
             len(manifest["documents"]), manifest["ac"], manifest["ac_name"], args.out_dir)
    for d in manifest["documents"]:
        log.info("  %-16s %s", d["kind"], d["path"])
    log.info("manifest: %s", Path(args.out_dir) / "manifest.json")
    return 0


if __name__ == "__main__":
    sys.exit(main())
