-- 0023: the real Giridih Form 20 - postal ballots, per-candidate keys, origin flag
--
-- The Giridih Form 20 for VS-2019 and VS-2024 (db/seed/form20/) is the first
-- real booth-level result in this database, and it needs three things the
-- schema did not have:
--
-- 1. Postal ballots. Booth rows are EVM-only; the declared result adds the
--    "Total Postal Ballot Votes" row. Postal votes per candidate (NOTA too)
--    are seeded as result_ac_total metric 'postal', postal rejections as the
--    new metric 'postal_rejected'. mv_ac_summary now ranks winner and runner-up
--    on EVM + postal and reports evm_votes / postal_votes / rejected beside the
--    totals. With no postal rows the figures are exactly what they were.
-- 2. Candidates whose party the source does not record (party UNK). The
--    `contestant` key was per candidate only for IND, so every UNK candidate
--    would have been merged into one pseudo-candidate. It is per candidate now.
-- 3. source_doc.is_synthetic, so the API can say whether figures come from a
--    real document or from ingest/mock_documents.py.
--
-- Also: mv_ac_summary.electors falls back to the published AC figure, with
-- electors_source saying which, and votes_polled_published is exposed so a
-- reader can compare. Every view is dropped and recreated (bodies otherwise
-- verbatim from 0015 and 0020) because mv_result_booth_candidate is at the root
-- of the dependency chain; grants are restored as in 0021.

ALTER TABLE source_doc ADD COLUMN IF NOT EXISTS is_synthetic BOOLEAN NOT NULL DEFAULT false;
COMMENT ON COLUMN source_doc.is_synthetic IS
    'true for documents generated by ingest/mock_documents.py; figures loaded from them '
    'are not evidence about any constituency.';

DO $$
DECLARE c TEXT;
BEGIN
    FOR c IN SELECT conname FROM pg_constraint
             WHERE conrelid = 'result_ac_total'::regclass AND contype = 'c'
               AND pg_get_constraintdef(oid) LIKE '%metric%'
    LOOP
        EXECUTE format('ALTER TABLE result_ac_total DROP CONSTRAINT %I', c);
    END LOOP;
END
$$;
ALTER TABLE result_ac_total ADD CONSTRAINT result_ac_total_metric_check CHECK (metric IN
    ('votes', 'nota', 'total_valid', 'electors', 'rejected', 'postal',
     'postal_rejected', 'votes_polled'));

DROP MATERIALIZED VIEW IF EXISTS mv_ac_summary CASCADE;
DROP MATERIALIZED VIEW IF EXISTS mv_area_rollup CASCADE;
DROP MATERIALIZED VIEW IF EXISTS mv_booth_priority CASCADE;
DROP MATERIALIZED VIEW IF EXISTS mv_new_voter_share CASCADE;
DROP MATERIALIZED VIEW IF EXISTS mv_floating_vote CASCADE;
DROP MATERIALIZED VIEW IF EXISTS mv_volatility CASCADE;
DROP MATERIALIZED VIEW IF EXISTS mv_transfer_ls_vs CASCADE;
DROP MATERIALIZED VIEW IF EXISTS mv_swing_vanished CASCADE;
DROP MATERIALIZED VIEW IF EXISTS mv_swing CASCADE;
DROP MATERIALIZED VIEW IF EXISTS mv_result_booth_wide CASCADE;
DROP MATERIALIZED VIEW IF EXISTS mv_booth_party_share CASCADE;
DROP MATERIALIZED VIEW IF EXISTS mv_booth_totals CASCADE;
DROP MATERIALIZED VIEW IF EXISTS mv_result_booth_party CASCADE;
DROP MATERIALIZED VIEW IF EXISTS mv_result_booth_candidate CASCADE;

CREATE MATERIALIZED VIEW mv_result_booth_candidate AS
SELECT r.ac_id,
       r.election_id,
       e.label            AS election_label,
       e.type             AS election_type,
       e.year             AS election_year,
       x.booth_uid,
       r.candidate_id,
       c.name_en          AS candidate_name,
       c.party_id,
       p.abbr             AS party,
       -- A candidate key that stays distinct for independents, who must compete
       -- individually rather than as a bucket (D3).
       -- Per candidate for independents and for candidates whose party the
       -- source does not record (UNK, 0023): either way they are separate
       -- people and must rank separately, never as one merged bucket.
       CASE WHEN p.abbr IN ('IND', 'UNK') THEN p.abbr || ':' || c.name_en
            ELSE p.abbr END AS contestant,
       SUM(r.votes)::INT  AS votes,
       -- Carried so downstream views can decide whether this booth's numbers
       -- may be compared across years.
       MIN(x.confidence)  AS crosswalk_confidence,
       BOOL_AND(x.reviewed) AS crosswalk_reviewed,
       MIN(x.match_method) AS crosswalk_method
FROM result_booth r
JOIN election e         ON e.election_id = r.election_id
JOIN booth_crosswalk x  ON x.election_id = r.election_id AND x.ps_number = r.ps_number
JOIN candidate c        ON c.candidate_id = r.candidate_id
LEFT JOIN party p       ON p.party_id = c.party_id
GROUP BY r.ac_id, r.election_id, e.label, e.type, e.year, x.booth_uid,
         r.candidate_id, c.name_en, c.party_id, p.abbr;

CREATE UNIQUE INDEX mv_rbc_key
    ON mv_result_booth_candidate (ac_id, election_id, booth_uid, candidate_id);
CREATE INDEX mv_rbc_booth ON mv_result_booth_candidate (ac_id, booth_uid);

CREATE MATERIALIZED VIEW mv_result_booth_party AS
SELECT ac_id, election_id, election_label, election_type, election_year,
       booth_uid, party_id, party,
       SUM(votes)::INT AS votes
FROM mv_result_booth_candidate
GROUP BY ac_id, election_id, election_label, election_type, election_year,
         booth_uid, party_id, party;

CREATE UNIQUE INDEX mv_rbp_key
    ON mv_result_booth_party (ac_id, election_id, booth_uid, COALESCE(party_id, -1));

-- valid_votes: candidate votes INCLUDING NOTA (metrics.valid_votes).

CREATE MATERIALIZED VIEW mv_booth_totals AS
SELECT ac_id, election_id, election_label, election_type, election_year, booth_uid,
       SUM(votes)::INT                                        AS valid_votes,
       SUM(votes) FILTER (WHERE party = 'NOTA')::INT           AS nota,
       SUM(votes) FILTER (WHERE party <> 'NOTA' OR party IS NULL)::INT AS candidate_votes,
       COUNT(*) FILTER (WHERE party <> 'NOTA' OR party IS NULL) AS contestants
FROM mv_result_booth_party
GROUP BY ac_id, election_id, election_label, election_type, election_year, booth_uid;

CREATE UNIQUE INDEX mv_bt_key ON mv_booth_totals (ac_id, election_id, booth_uid);

-- share_pct, with NOTA inside the denominator.

CREATE MATERIALIZED VIEW mv_booth_party_share AS
SELECT p.ac_id, p.election_id, p.election_label, p.election_type, p.election_year,
       p.booth_uid, p.party_id, p.party, p.votes,
       t.valid_votes,
       metric_share_pct(p.votes, t.valid_votes) AS share_pct
FROM mv_result_booth_party p
JOIN mv_booth_totals t
  ON t.ac_id = p.ac_id AND t.election_id = p.election_id AND t.booth_uid = p.booth_uid;

CREATE UNIQUE INDEX mv_bps_key
    ON mv_booth_party_share (ac_id, election_id, booth_uid, COALESCE(party_id, -1));
CREATE INDEX mv_bps_party ON mv_booth_party_share (ac_id, party, election_year);

CREATE MATERIALIZED VIEW mv_result_booth_wide AS
WITH ranked AS (
    -- Rank contestants, NOTA excluded. Ordered by name after votes so a tie is
    -- deterministic between refreshes rather than dependent on scan order.
    SELECT ac_id, election_id, booth_uid, contestant, party, candidate_name, votes,
           ROW_NUMBER() OVER (PARTITION BY ac_id, election_id, booth_uid
                              ORDER BY votes DESC, contestant) AS rn
    FROM mv_result_booth_candidate
    WHERE party IS DISTINCT FROM 'NOTA'
), pivot AS (
    SELECT ac_id, election_id, booth_uid,
           SUM(votes) FILTER (WHERE party = 'JMM')::INT  AS jmm,
           SUM(votes) FILTER (WHERE party = 'BJP')::INT  AS bjp,
           SUM(votes) FILTER (WHERE party = 'AJSU')::INT AS ajsu,
           SUM(votes) FILTER (WHERE party = 'JLKM')::INT AS jlkm,
           SUM(votes) FILTER (WHERE party = 'INC')::INT  AS inc,
           SUM(votes) FILTER (WHERE party = 'RJD')::INT  AS rjd,
           SUM(votes) FILTER (WHERE party = 'JVM')::INT  AS jvm,
           SUM(votes) FILTER (WHERE party NOT IN
               ('JMM','BJP','AJSU','JLKM','INC','RJD','JVM','NOTA')
               OR party IS NULL)::INT                    AS others
    FROM mv_result_booth_party
    GROUP BY ac_id, election_id, booth_uid
), meta AS (
    SELECT m.ac_id, m.election_id, x.booth_uid,
           SUM(m.electors)::INT    AS manual_electors,
           SUM(m.rejected)::INT    AS rejected,
           SUM(m.total_valid)::INT AS printed_valid,
           string_agg(m.ps_number::TEXT, ',' ORDER BY m.ps_number) AS ps_numbers,
           MIN(m.source_doc)       AS source_doc,
           MIN(m.source_page)      AS source_page
    FROM result_booth_meta m
    JOIN booth_crosswalk x
      ON x.election_id = m.election_id AND x.ps_number = m.ps_number
    GROUP BY m.ac_id, m.election_id, x.booth_uid
), roll_electors AS (
    -- Electors per booth per election, from the roll revision that election is
    -- linked to. Finding N5: `metric_turnout_pct` documents its denominator as
    -- coming "from the linked roll snapshot, never from Form 20" - which is why
    -- `election_roll_link` exists at all - but this view read
    -- `result_booth_meta.electors`, a column no loader writes. So turnout_pct
    -- was NULL for every booth in every AC by construction, and the comment two
    -- screens below said the opposite. The Overview turnout tile, the booth
    -- table column, the area rollup and the map all rendered an em dash and
    -- there was no input that could have changed it.
    SELECT e.ac_id, e.election_id, s.booth_uid, s.electors
    FROM election_roll_link l
    JOIN election e      ON e.election_id = l.election_id
    JOIN roll_snapshot s ON s.revision_id = l.revision_id
), lineage AS (
    -- One row per new booth per old election, so the wide row can say that a
    -- comparison is on an aggregated group rather than a like-for-like booth.
    SELECT new_booth_uid, MIN(kind) AS kind, SUM(weight) AS weight
    FROM booth_lineage
    GROUP BY new_booth_uid
)
SELECT t.ac_id,
       t.election_id,
       t.election_label,
       t.election_type,
       t.election_year,
       t.booth_uid,
       b.area_id,
       a.block_id,
       m.ps_numbers,
       -- Roll first, then an operator-entered figure on result_booth_meta.
       -- NULL when neither exists, which is the honest answer and what B4 asks
       -- for: a booth whose electorate is unknown reports no turnout rather
       -- than a turnout computed against zero.
       COALESCE(re.electors, m.manual_electors) AS electors,
       CASE WHEN re.electors IS NOT NULL        THEN 'roll'
            WHEN m.manual_electors IS NOT NULL  THEN 'manual'
       END AS electors_source,
       t.valid_votes,
       -- votes_polled = valid + rejected; tendered excluded by construction.
       metric_votes_polled(t.valid_votes, m.rejected)::INT AS votes_polled,
       m.rejected,
       t.nota,
       -- Kept so an operator can see the printed total next to the computed one.
       -- validate.py asserts they agree; a divergence means a parse problem, and
       -- silently preferring one was how D1 hid.
       m.printed_valid,
       pv.jmm, pv.bjp, pv.ajsu, pv.jlkm, pv.inc, pv.rjd, pv.jvm, pv.others,
       w.contestant  AS winner_party,
       w.candidate_name AS winner_candidate,
       w.votes       AS winner_votes,
       ru.contestant AS runner_party,
       ru.votes      AS runner_votes,
       t.contestants,
       -- margin: NULL with fewer than two contestants, never 0. These three
       -- columns used to spell the same quotient out four times between them,
       -- which is how D1 survived - correcting the denominator in one CASE arm
       -- and not the others is a one-character mistake that no test can tell
       -- apart from correctness.
       metric_margin_votes(w.votes, ru.votes, t.contestants)::INT AS margin_votes,
       metric_margin_pct(w.votes, ru.votes, t.contestants,
                         t.valid_votes) AS margin_pct,
       -- signed_margin_pct: + if the contest pair's first party won, - if the
       -- second, NULL if neither. Drives the map's diverging ramp (F1).
       metric_signed_margin_pct(w.contestant, w.votes, ru.votes, t.contestants,
                                t.valid_votes, pa.abbr,
                                pb.abbr) AS signed_margin_pct,
       pa.abbr AS contest_party_a,
       pb.abbr AS contest_party_b,
       -- turnout: electors from the linked roll snapshot (see roll_electors).
       metric_turnout_pct(metric_votes_polled(t.valid_votes, m.rejected),
                          COALESCE(re.electors, m.manual_electors)) AS turnout_pct,
       lin.kind   AS lineage_kind,
       lin.weight AS lineage_weight,
       m.source_doc,
       m.source_page
FROM mv_booth_totals t
JOIN booth b        ON b.booth_uid = t.booth_uid
JOIN area a         ON a.area_id = b.area_id
JOIN election e     ON e.election_id = t.election_id
LEFT JOIN pivot pv  ON pv.ac_id = t.ac_id AND pv.election_id = t.election_id
                   AND pv.booth_uid = t.booth_uid
LEFT JOIN meta m    ON m.ac_id = t.ac_id AND m.election_id = t.election_id
                   AND m.booth_uid = t.booth_uid
LEFT JOIN roll_electors re ON re.ac_id = t.ac_id AND re.election_id = t.election_id
                   AND re.booth_uid = t.booth_uid
LEFT JOIN ranked w  ON w.ac_id = t.ac_id AND w.election_id = t.election_id
                   AND w.booth_uid = t.booth_uid AND w.rn = 1
LEFT JOIN ranked ru ON ru.ac_id = t.ac_id AND ru.election_id = t.election_id
                   AND ru.booth_uid = t.booth_uid AND ru.rn = 2
LEFT JOIN ac_contest ct ON ct.ac_id = t.ac_id AND ct.event_id = e.event_id
LEFT JOIN party pa  ON pa.party_id = ct.party_a
LEFT JOIN party pb  ON pb.party_id = ct.party_b
LEFT JOIN lineage lin ON lin.new_booth_uid = t.booth_uid;

CREATE UNIQUE INDEX mv_rbw_key ON mv_result_booth_wide (ac_id, election_id, booth_uid);
CREATE INDEX mv_rbw_label ON mv_result_booth_wide (ac_id, election_label);
CREATE INDEX mv_rbw_area  ON mv_result_booth_wide (ac_id, area_id);

CREATE MATERIALIZED VIEW mv_swing AS
WITH shares AS (
    SELECT s.ac_id, s.booth_uid, s.party_id, s.party, s.election_type,
           s.election_year, s.election_id, s.election_label, s.share_pct, s.votes,
           LAG(s.share_pct) OVER w  AS prev_share_pct,
           LAG(s.votes)     OVER w  AS prev_votes,
           LAG(s.election_id) OVER w AS prev_election_id,
           LAG(s.election_label) OVER w AS prev_election_label
    FROM mv_booth_party_share s
    WHERE s.party IS DISTINCT FROM 'NOTA'
    WINDOW w AS (PARTITION BY s.ac_id, s.booth_uid, s.party_id, s.election_type
                 ORDER BY s.election_year)
), quality AS (
    SELECT ac_id, election_id, booth_uid,
           MIN(crosswalk_confidence) AS confidence,
           BOOL_AND(crosswalk_reviewed) AS reviewed
    FROM mv_result_booth_candidate
    GROUP BY ac_id, election_id, booth_uid
)
SELECT sh.ac_id, sh.booth_uid, sh.party_id, sh.party, sh.election_type,
       sh.election_id, sh.election_label, sh.election_year,
       sh.prev_election_id, sh.prev_election_label,
       sh.share_pct, sh.prev_share_pct,
       -- NULL, not 0, when there is no prior election for this booth (D2), when
       -- the crosswalk is weak and unreviewed, or when the booth split or merged
       -- and the lineage group has not been aggregated. `false` is
       -- lineage_aggregated: nothing in the schema aggregates lineage groups
       -- yet, and the argument is passed explicitly rather than omitted so the
       -- day something does, every call site is already findable.
       metric_swing_pct(sh.share_pct, sh.prev_share_pct, q.confidence,
                        q.reviewed, w.lineage_kind, false) AS swing_pct,
       -- The same gate, from the same function, so swing votes and swing share
       -- cannot come to different conclusions about whether this booth is
       -- comparable at all. They previously restated the two-clause rule
       -- verbatim, one after the other.
       CASE WHEN sh.prev_votes IS NOT NULL
                 AND metric_comparison_allowed(q.confidence, q.reviewed,
                                               w.lineage_kind, false)
            THEN (sh.votes - sh.prev_votes)::INT
       END AS swing_votes,
       q.confidence AS crosswalk_confidence,
       q.reviewed   AS crosswalk_reviewed,
       w.lineage_kind
FROM shares sh
LEFT JOIN quality q ON q.ac_id = sh.ac_id AND q.election_id = sh.election_id
                   AND q.booth_uid = sh.booth_uid
LEFT JOIN mv_result_booth_wide w ON w.ac_id = sh.ac_id
                                AND w.election_id = sh.election_id
                                AND w.booth_uid = sh.booth_uid;

CREATE UNIQUE INDEX mv_swing_key
    ON mv_swing (ac_id, booth_uid, COALESCE(party_id, -1), election_id);

-- D9: a party that contested the earlier election and not the later one has no
-- row in the later one, so its collapse never appeared. JVM is exactly this -
-- it merged into BJP in 2020, so a 2019-to-2024 swing table showed BJP's gain
-- with no corresponding JVM loss. These are the missing rows.

CREATE MATERIALIZED VIEW mv_swing_vanished AS
WITH pairs AS (
    SELECT DISTINCT e1.ac_id, e1.election_id AS prev_election_id,
           e2.election_id AS election_id, e1.type AS election_type,
           e1.label AS prev_election_label, e2.label AS election_label, e2.year
    FROM election e1
    JOIN election e2 ON e2.ac_id = e1.ac_id AND e2.type = e1.type AND e2.year > e1.year
    WHERE NOT EXISTS (SELECT 1 FROM election mid
                       WHERE mid.ac_id = e1.ac_id AND mid.type = e1.type
                         AND mid.year > e1.year AND mid.year < e2.year)
)
SELECT p.ac_id, prev.booth_uid, prev.party_id, prev.party, p.election_type,
       p.election_id, p.election_label, p.year AS election_year,
       p.prev_election_id, p.prev_election_label,
       0.0::NUMERIC       AS share_pct,
       prev.share_pct     AS prev_share_pct,
       -- Routed through the same function, with the same gate, as mv_swing.
       -- This subtracted directly before, so a vanished party's collapse was
       -- reported even at a booth whose crosswalk was too weak to carry the
       -- surviving parties' swings: the two halves of one swing table
       -- disagreeing about whether the comparison was admissible, with the
       -- half that lacked the gate being the half that reports a party
       -- dropping to zero.
       metric_swing_pct(0.0::NUMERIC, prev.share_pct, q.confidence, q.reviewed,
                        w.lineage_kind, false) AS swing_pct,
       CASE WHEN metric_comparison_allowed(q.confidence, q.reviewed,
                                           w.lineage_kind, false)
            THEN (0 - prev.votes)::INT
       END AS swing_votes
FROM pairs p
JOIN mv_booth_party_share prev
  ON prev.ac_id = p.ac_id AND prev.election_id = p.prev_election_id
LEFT JOIN (
    SELECT ac_id, election_id, booth_uid,
           MIN(crosswalk_confidence)    AS confidence,
           BOOL_AND(crosswalk_reviewed) AS reviewed
    FROM mv_result_booth_candidate
    GROUP BY ac_id, election_id, booth_uid
) q ON q.ac_id = p.ac_id AND q.election_id = p.election_id
   AND q.booth_uid = prev.booth_uid
LEFT JOIN mv_result_booth_wide w ON w.ac_id = p.ac_id
                                AND w.election_id = p.election_id
                                AND w.booth_uid = prev.booth_uid
WHERE prev.party IS DISTINCT FROM 'NOTA'
  AND NOT EXISTS (
      SELECT 1 FROM mv_booth_party_share now
       WHERE now.ac_id = p.ac_id AND now.election_id = p.election_id
         AND now.booth_uid = prev.booth_uid
         AND now.party_id IS NOT DISTINCT FROM prev.party_id
  )
  -- Only where the later election actually has results for this booth;
  -- otherwise "did not contest" is indistinguishable from "not loaded".
  AND EXISTS (
      SELECT 1 FROM mv_booth_totals t
       WHERE t.ac_id = p.ac_id AND t.election_id = p.election_id
         AND t.booth_uid = prev.booth_uid
  );

CREATE UNIQUE INDEX mv_swing_vanished_key
    ON mv_swing_vanished (ac_id, booth_uid, COALESCE(party_id, -1), election_id);

CREATE MATERIALIZED VIEW mv_transfer_ls_vs AS
SELECT COALESCE(ls.ac_id, vs.ac_id)         AS ac_id,
       COALESCE(ls.election_year, vs.election_year) AS year,
       COALESCE(ls.booth_uid, vs.booth_uid) AS booth_uid,
       COALESCE(ls.party, vs.party)         AS party,
       COALESCE(ls.party_id, vs.party_id)   AS party_id,
       ls.votes      AS ls_votes,
       vs.votes      AS vs_votes,
       ls.share_pct  AS ls_share_pct,
       vs.share_pct  AS vs_share_pct,
       (vs.votes - ls.votes)::INT AS delta_votes,
       -- transfer_delta: NULL when either leg is missing, never a full share
       -- masquerading as a swing.
       metric_transfer_delta(vs.share_pct, ls.share_pct) AS delta_share_pct
FROM (SELECT * FROM mv_booth_party_share WHERE election_type = 'LS') ls
FULL OUTER JOIN (SELECT * FROM mv_booth_party_share WHERE election_type = 'VS') vs
  ON vs.ac_id = ls.ac_id AND vs.booth_uid = ls.booth_uid
 AND vs.election_year = ls.election_year
 AND vs.party_id IS NOT DISTINCT FROM ls.party_id;

CREATE UNIQUE INDEX mv_transfer_key
    ON mv_transfer_ls_vs (ac_id, year, booth_uid, COALESCE(party_id, -1));

-- floating_pct: the Pedersen index, and NULL - not 50.00 - when only one poll
-- type exists for that year at that booth (D4). The old view's FULL OUTER JOIN
-- made every party's delta equal its full share in the single poll that
-- existed, so the index came to exactly 100/2 for every booth in the
-- constituency, appeared on the map and in the priority score, looked like a
-- finding, and flattened PERCENT_RANK so the priority score silently lost its
-- 0.20 floating-vote term.

CREATE MATERIALIZED VIEW mv_volatility AS
SELECT ac_id, booth_uid,
       COUNT(signed_margin_pct)        AS years_available,
       -- NULL with fewer than two years, enforced inside metric_volatility so
       -- the rule is stated once instead of beside each use of it. ARRAY_AGG
       -- rather than a direct stddev_samp because the function is what
       -- analytics.metrics.volatility is checked against.
       metric_volatility(ARRAY_AGG(signed_margin_pct)) AS margin_stddev,
       ROUND(AVG(signed_margin_pct)::NUMERIC, 2) AS margin_mean
FROM mv_result_booth_wide
WHERE election_type = 'VS'
GROUP BY ac_id, booth_uid;

CREATE UNIQUE INDEX mv_volatility_key ON mv_volatility (ac_id, booth_uid);

CREATE MATERIALIZED VIEW mv_floating_vote AS
WITH legs AS (
    SELECT ac_id, election_year AS year, booth_uid,
           COUNT(DISTINCT election_type) AS poll_types
    FROM mv_booth_party_share
    WHERE election_type IN ('LS', 'VS')
    GROUP BY ac_id, election_year, booth_uid
)
SELECT t.ac_id, t.year, t.booth_uid,
       -- The sum is an aggregate and stays here; the halving and the
       -- one-poll-type NULL rule live in the function.
       metric_floating_pct(
           SUM(ABS(COALESCE(t.vs_share_pct, 0) - COALESCE(t.ls_share_pct, 0))),
           l.poll_types) AS floating_pct,
       l.poll_types
FROM mv_transfer_ls_vs t
JOIN legs l ON l.ac_id = t.ac_id AND l.year = t.year AND l.booth_uid = t.booth_uid
GROUP BY t.ac_id, t.year, t.booth_uid, l.poll_types;

CREATE UNIQUE INDEX mv_floating_key ON mv_floating_vote (ac_id, year, booth_uid);

CREATE MATERIALIZED VIEW mv_new_voter_share AS
WITH windows AS (
    -- The window is (linked roll of the previous election of this type, linked
    -- roll of this one]. Both ends must exist or every figure downstream is
    -- NULL - which is the honest answer, and what B1 got wrong by leaving the
    -- baseline CTE empty and reporting 0 additions everywhere.
    -- ac_id from the election, not from the link table: election_roll_link is
    -- (election_id, revision_id) and has no ac_id. This said `l.ac_id`, so
    -- 0015 could not be applied at all - the first `apply_migrations` run
    -- against any database would have stopped here. It survived review because
    -- nothing had ever executed this file.
    SELECT e.ac_id, l.election_id,
           e.type, e.year,
           r.revision_date AS window_end,
           LAG(r.revision_date) OVER (PARTITION BY e.ac_id, e.type ORDER BY e.year)
               AS window_start,
           l.revision_id   AS end_revision_id
    FROM election_roll_link l
    JOIN election e      ON e.election_id = l.election_id
    JOIN roll_revision r ON r.revision_id = l.revision_id
), changes AS (
    SELECT w.ac_id, w.election_id, c.booth_uid,
           SUM(c.additions)::INT     AS additions,
           SUM(c.deletions)::INT     AS deletions,
           SUM(c.modifications)::INT AS modifications
    FROM windows w
    JOIN roll_change c   ON c.ac_id = w.ac_id
    JOIN roll_revision r ON r.revision_id = c.revision_id
    WHERE w.window_start IS NOT NULL
      AND r.revision_date > w.window_start
      AND r.revision_date <= w.window_end
    GROUP BY w.ac_id, w.election_id, c.booth_uid
), electors_at AS (
    SELECT w.ac_id, w.election_id, s.booth_uid,
           s.electors AS electors_end
    FROM windows w
    JOIN roll_snapshot s ON s.revision_id = w.end_revision_id
), electors_start AS (
    -- The latest mother roll on or before the window start, one row per booth.
    -- 0015 joined every mother roll dated on or before it, so an AC with two
    -- produced duplicate (ac, election, booth) rows and the refresh failed on
    -- the unique index mv_nvs_key.
    SELECT DISTINCT ON (w.ac_id, w.election_id, s.booth_uid)
           w.ac_id, w.election_id, s.booth_uid, s.electors AS electors_start
    FROM windows w
    JOIN roll_revision r ON r.ac_id = w.ac_id AND r.is_mother
                        AND r.revision_date <= w.window_start
    JOIN roll_snapshot s ON s.revision_id = r.revision_id
    WHERE w.window_start IS NOT NULL
    ORDER BY w.ac_id, w.election_id, s.booth_uid, r.revision_date DESC
)
SELECT w.ac_id, w.election_id, b.booth_uid,
       c.additions, c.deletions, c.modifications,
       ee.electors_end AS electors,
       es.electors_start,
       -- new_voter_pct: additions / electors at window end. NULL when either
       -- roll is missing.
       metric_new_voter_pct(c.additions, ee.electors_end) AS new_voter_pct,
       -- net_roll_change_pct: (additions - deletions) / electors at window start.
       metric_net_roll_change_pct(c.additions, c.deletions,
                                  es.electors_start) AS net_roll_change_pct
FROM windows w
JOIN booth b ON b.ac_id = w.ac_id
LEFT JOIN changes c        ON c.ac_id = w.ac_id AND c.election_id = w.election_id
                          AND c.booth_uid = b.booth_uid
LEFT JOIN electors_at ee   ON ee.ac_id = w.ac_id AND ee.election_id = w.election_id
                          AND ee.booth_uid = b.booth_uid
LEFT JOIN electors_start es ON es.ac_id = w.ac_id AND es.election_id = w.election_id
                           AND es.booth_uid = b.booth_uid;

CREATE UNIQUE INDEX mv_nvs_key ON mv_new_voter_share (ac_id, election_id, booth_uid);

CREATE MATERIALIZED VIEW mv_booth_priority AS
WITH baseline AS (
    SELECT w.*
    FROM mv_result_booth_wide w
    JOIN election e ON e.election_id = w.election_id AND e.is_baseline
), inputs AS (
    SELECT b.ac_id, b.booth_uid, b.election_id, b.election_label, b.area_id,
           b.electors, b.turnout_pct, b.margin_pct, b.margin_votes,
           b.signed_margin_pct, b.winner_party, b.runner_party,
           n.new_voter_pct, n.additions,
           f.floating_pct,
           v.margin_stddev,
           v.years_available
    FROM baseline b
    LEFT JOIN mv_new_voter_share n ON n.ac_id = b.ac_id AND n.booth_uid = b.booth_uid
                                  AND n.election_id = b.election_id
    LEFT JOIN mv_floating_vote f   ON f.ac_id = b.ac_id AND f.booth_uid = b.booth_uid
                                  AND f.year = b.election_year
    LEFT JOIN mv_volatility v      ON v.ac_id = b.ac_id AND v.booth_uid = b.booth_uid
), ranked AS (
    SELECT i.*,
           -- closeness = 1 - margin percentile, so the tightest booth scores 1.
           CASE WHEN i.margin_pct IS NOT NULL
                 AND COUNT(i.margin_pct) OVER (PARTITION BY i.ac_id) >= 2
                THEN 1 - PERCENT_RANK() OVER (PARTITION BY i.ac_id, i.margin_pct IS NULL
                                              ORDER BY i.margin_pct)
           END AS closeness_rank,
           CASE WHEN i.new_voter_pct IS NOT NULL
                 AND COUNT(i.new_voter_pct) OVER (PARTITION BY i.ac_id) >= 2
                THEN PERCENT_RANK() OVER (PARTITION BY i.ac_id, i.new_voter_pct IS NULL
                                          ORDER BY i.new_voter_pct)
           END AS new_voter_rank,
           CASE WHEN i.floating_pct IS NOT NULL
                 AND COUNT(i.floating_pct) OVER (PARTITION BY i.ac_id) >= 2
                THEN PERCENT_RANK() OVER (PARTITION BY i.ac_id, i.floating_pct IS NULL
                                          ORDER BY i.floating_pct)
           END AS floating_rank,
           CASE WHEN i.margin_stddev IS NOT NULL
                 AND COUNT(i.margin_stddev) OVER (PARTITION BY i.ac_id) >= 2
                THEN PERCENT_RANK() OVER (PARTITION BY i.ac_id, i.margin_stddev IS NULL
                                          ORDER BY i.margin_stddev)
           END AS volatility_rank
    FROM inputs i
), weighted AS (
    SELECT r.*,
           -- Missing inputs are dropped and the remaining weights
           -- renormalised, both inside the generated functions, so the four
           -- weights are written down in exactly one place in the codebase.
           metric_priority_score(r.closeness_rank, r.new_voter_rank,
                                 r.floating_rank, r.volatility_rank) AS score,
           metric_priority_weight(r.closeness_rank, r.new_voter_rank,
                                  r.floating_rank,
                                  r.volatility_rank) AS weight_used,
           -- Which inputs actually contributed. Two of the four were constant
           -- in the audited system - new voters 0 everywhere and floating 50.00
           -- everywhere - so a score that looked like a four-factor ranking was
           -- a two-factor one with no way to tell from the output.
           ARRAY_REMOVE(ARRAY[
               CASE WHEN r.closeness_rank  IS NOT NULL THEN 'closeness' END,
               CASE WHEN r.new_voter_rank  IS NOT NULL THEN 'new_voter_pct' END,
               CASE WHEN r.floating_rank   IS NOT NULL THEN 'floating_pct' END,
               CASE WHEN r.volatility_rank IS NOT NULL THEN 'volatility' END
           ], NULL) AS inputs_used
    FROM ranked r
)
SELECT ac_id, booth_uid, election_id, election_label, area_id,
       electors, turnout_pct, margin_pct, margin_votes, signed_margin_pct,
       winner_party, runner_party, new_voter_pct, additions, floating_pct,
       margin_stddev, years_available, inputs_used, weight_used,
       score AS priority_score,
       -- Quartile over the score itself, so the ranking and the number shown
       -- beside it cannot be computed from different expressions.
       CASE WHEN score IS NOT NULL
            THEN NTILE(4) OVER (PARTITION BY ac_id ORDER BY score DESC)
       END AS priority_quartile
FROM weighted;

CREATE UNIQUE INDEX mv_priority_key ON mv_booth_priority (ac_id, booth_uid);
CREATE INDEX mv_priority_score ON mv_booth_priority (ac_id, priority_score DESC);

CREATE MATERIALIZED VIEW mv_area_rollup AS
SELECT w.ac_id, w.election_id, w.election_label, w.election_type, w.election_year,
       a.area_id, a.name_en AS area_name_en, a.name_hi AS area_name_hi, a.kind AS area_kind,
       a.block_id, bl.name_en AS block_name_en,
       COUNT(*)                     AS booths,
       SUM(w.electors)::INT         AS electors,
       SUM(w.valid_votes)::INT      AS valid_votes,
       SUM(w.votes_polled)::INT     AS votes_polled,
       SUM(w.nota)::INT             AS nota,
       SUM(w.jmm)::INT AS jmm, SUM(w.bjp)::INT AS bjp, SUM(w.ajsu)::INT AS ajsu,
       SUM(w.jlkm)::INT AS jlkm, SUM(w.inc)::INT AS inc, SUM(w.rjd)::INT AS rjd,
       SUM(w.jvm)::INT AS jvm, SUM(w.others)::INT AS others,
       metric_share_pct(SUM(w.jmm)::INT, SUM(w.valid_votes)::INT) AS jmm_pct,
       metric_share_pct(SUM(w.bjp)::INT, SUM(w.valid_votes)::INT) AS bjp_pct,
       -- Turnout only where every booth in the area knows its electors;
       -- otherwise the denominator is a partial sum and the percentage is
       -- quietly wrong rather than absent.
       CASE WHEN COUNT(*) = COUNT(w.electors)
            THEN metric_turnout_pct(SUM(w.votes_polled)::INT,
                                    SUM(w.electors)::INT)
       END AS turnout_pct,
       COUNT(w.electors) AS booths_with_electors
FROM mv_result_booth_wide w
JOIN area a  ON a.area_id = w.area_id
JOIN block bl ON bl.block_id = a.block_id
GROUP BY w.ac_id, w.election_id, w.election_label, w.election_type, w.election_year,
         a.area_id, a.name_en, a.name_hi, a.kind, a.block_id, bl.name_en;

CREATE UNIQUE INDEX mv_area_rollup_key ON mv_area_rollup (ac_id, election_id, area_id);

CREATE MATERIALIZED VIEW mv_ac_summary AS
WITH booth_totals AS (
    -- EVM: everything counted at the polling stations.
    SELECT w.ac_id, w.election_id, w.election_label, w.election_type, w.election_year,
           COUNT(*)                  AS booths,
           SUM(w.valid_votes)::INT   AS evm_valid,
           SUM(w.nota)::INT          AS evm_nota,
           SUM(w.rejected)::INT      AS evm_rejected,
           SUM(w.electors)::INT      AS electors,
           COUNT(w.electors)         AS booths_with_electors
    FROM mv_result_booth_wide w
    GROUP BY w.ac_id, w.election_id, w.election_label, w.election_type, w.election_year
), postal_candidate AS (
    -- Postal ballots per candidate (NOTA included), from the Form 20's
    -- "Total Postal Ballot Votes" row. Booth rows are EVM-only, so without
    -- these the AC result was short of the declared one by every postal vote.
    SELECT t.election_id, t.candidate_id, t.value AS postal
    FROM result_ac_total t
    WHERE t.metric = 'postal' AND t.candidate_id IS NOT NULL
), postal_sum AS (
    SELECT pc.election_id,
           SUM(pc.postal)::INT                                    AS postal_valid,
           (SUM(pc.postal) FILTER (WHERE p.abbr = 'NOTA'))::INT   AS postal_nota
    FROM postal_candidate pc
    JOIN candidate c ON c.candidate_id = pc.candidate_id
    LEFT JOIN party p ON p.party_id = c.party_id
    GROUP BY pc.election_id
), published AS (
    SELECT election_id,
           MAX(value) FILTER (WHERE metric = 'postal_rejected') AS postal_rejected,
           MAX(value) FILTER (WHERE metric = 'electors')        AS electors,
           MAX(value) FILTER (WHERE metric = 'votes_polled')    AS votes_polled
    FROM result_ac_total
    WHERE candidate_id IS NULL
    GROUP BY election_id
), totals AS (
    SELECT bt.*,
           bt.evm_valid + COALESCE(ps.postal_valid, 0)                      AS valid_votes,
           bt.evm_nota + COALESCE(ps.postal_nota, 0)                        AS nota,
           COALESCE(bt.evm_rejected, 0) + COALESCE(pb.postal_rejected, 0)   AS rejected,
           ps.postal_valid                                                  AS postal_votes,
           pb.electors                                                      AS electors_published,
           pb.votes_polled                                                  AS votes_polled_published
    FROM booth_totals bt
    LEFT JOIN postal_sum ps ON ps.election_id = bt.election_id
    LEFT JOIN published pb  ON pb.election_id = bt.election_id
), candidate_totals AS (
    -- Ranked on EVM + postal: the declared result. N2: per candidate on the
    -- `contestant` key, so independents and UNK candidates never merge.
    SELECT bc.ac_id, bc.election_id, bc.candidate_id, bc.candidate_name, bc.party,
           bc.contestant,
           SUM(bc.votes)::INT                                   AS evm_votes,
           (SUM(bc.votes) + COALESCE(MAX(pc.postal), 0))::INT   AS votes
    FROM mv_result_booth_candidate bc
    LEFT JOIN postal_candidate pc ON pc.candidate_id = bc.candidate_id
    WHERE bc.party IS DISTINCT FROM 'NOTA'
    GROUP BY bc.ac_id, bc.election_id, bc.candidate_id, bc.candidate_name, bc.party,
             bc.contestant
), party_totals AS (
    SELECT ac_id, election_id, party, SUM(votes)::INT AS votes
    FROM candidate_totals
    GROUP BY ac_id, election_id, party
), ranked AS (
    SELECT ct.*, ROW_NUMBER() OVER (PARTITION BY ct.ac_id, ct.election_id
                                    ORDER BY ct.votes DESC,
                                             ct.candidate_name) AS rn
    FROM candidate_totals ct
), crosswalk AS (
    -- Coverage denominator is ps_list_entry, not booth_crosswalk (C11).
    SELECT p.ac_id, p.election_id,
           COUNT(*) AS ps_rows,
           COUNT(x.booth_uid) AS matched,
           ROUND((100.0 * COUNT(x.booth_uid) / NULLIF(COUNT(*), 0))::NUMERIC, 2)
               AS coverage_pct
    FROM ps_list_entry p
    LEFT JOIN booth_crosswalk x
           ON x.election_id = p.election_id AND x.ps_number = p.ps_number
    GROUP BY p.ac_id, p.election_id
), contestants AS (
    SELECT ac_id, election_id, COUNT(*)::INT AS contestants
    FROM candidate_totals
    GROUP BY ac_id, election_id
), new_voters AS (
    SELECT ac_id, election_id,
           SUM(additions)::INT AS additions,
           metric_new_voter_pct(SUM(additions)::INT,
                                SUM(electors)::INT) AS new_voter_pct
    FROM mv_new_voter_share
    GROUP BY ac_id, election_id
), resolved AS (
    -- Electors: the linked roll when every booth has it, else the published
    -- AC figure (labelled), else the partial sum as before.
    SELECT t.*,
           CASE WHEN t.booths = t.booths_with_electors THEN t.electors
                ELSE COALESCE(t.electors_published, t.electors) END AS electors_used,
           CASE WHEN t.booths = t.booths_with_electors THEN 'roll'
                WHEN t.electors_published IS NOT NULL THEN 'published'
           END AS electors_source
    FROM totals t
)
SELECT t.ac_id, t.election_id, t.election_label, t.election_type, t.election_year AS year,
       e.is_baseline,
       t.booths,
       t.electors_used                  AS electors,
       t.electors_source,
       t.valid_votes,
       (t.valid_votes + t.rejected)::INT AS votes_polled,
       t.nota,
       t.rejected,
       t.evm_valid                      AS evm_votes,
       t.postal_votes,
       t.votes_polled_published,
       w.contestant     AS winner_party,
       w.candidate_name AS winner_candidate,
       w.votes          AS winner_votes,
       w.evm_votes      AS winner_evm_votes,
       r.contestant     AS runner_party,
       r.candidate_name AS runner_candidate,
       r.votes          AS runner_votes,
       r.evm_votes      AS runner_evm_votes,
       cn.contestants,
       metric_margin_votes(w.votes, r.votes, cn.contestants)::INT AS margin_votes,
       metric_margin_pct(w.votes, r.votes, cn.contestants,
                         t.valid_votes) AS margin_pct,
       metric_signed_margin_pct(w.contestant, w.votes, r.votes, cn.contestants,
                                t.valid_votes, pa.abbr,
                                pb.abbr) AS signed_margin_pct,
       CASE WHEN t.electors_source IS NOT NULL
            THEN metric_turnout_pct((t.valid_votes + t.rejected)::INT, t.electors_used)
       END AS turnout_pct,
       metric_share_pct(COALESCE(jl.votes, 0), t.valid_votes) AS jlkm_share_pct,
       nv.additions,
       nv.new_voter_pct,
       cw.coverage_pct AS crosswalk_coverage_pct,
       cw.ps_rows      AS ps_list_rows
FROM resolved t
JOIN election e  ON e.election_id = t.election_id
LEFT JOIN ranked w  ON w.ac_id = t.ac_id AND w.election_id = t.election_id AND w.rn = 1
LEFT JOIN ranked r  ON r.ac_id = t.ac_id AND r.election_id = t.election_id AND r.rn = 2
LEFT JOIN party_totals jl ON jl.ac_id = t.ac_id AND jl.election_id = t.election_id
                         AND jl.party = 'JLKM'
LEFT JOIN ac_contest ct ON ct.ac_id = t.ac_id AND ct.event_id = e.event_id
LEFT JOIN party pa ON pa.party_id = ct.party_a
LEFT JOIN party pb ON pb.party_id = ct.party_b
LEFT JOIN crosswalk cw ON cw.ac_id = t.ac_id AND cw.election_id = t.election_id
LEFT JOIN new_voters nv ON nv.ac_id = t.ac_id AND nv.election_id = t.election_id
LEFT JOIN contestants cn ON cn.ac_id = t.ac_id AND cn.election_id = t.election_id;

CREATE UNIQUE INDEX mv_ac_summary_key ON mv_ac_summary (ac_id, election_id);
CREATE INDEX mv_ac_summary_baseline ON mv_ac_summary (ac_id) WHERE is_baseline;

-- Grants are attached to objects, not names: restore them (see 0021).
GRANT SELECT ON
    mv_result_booth_party,
    mv_booth_party_share,
    mv_result_booth_wide,
    mv_swing,
    mv_transfer_ls_vs,
    mv_volatility,
    mv_new_voter_share,
    mv_floating_vote,
    mv_booth_priority,
    mv_area_rollup,
    mv_result_booth_candidate,
    mv_ac_summary,
    ac,
    election_event,
    ac_contest
TO giridih_ro;
